//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.06.14 at 09:30:07 AM CEST
//


package dk.oio.rep.ebxml.xml.schemas.dkcc._2003._02._13;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for _CountryIdentificationSchemeType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="_CountryIdentificationSchemeType">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="iso3166-alpha2"/>
 *     &lt;enumeration value="iso3166-alpha3"/>
 *     &lt;enumeration value="un-numeric3"/>
 *     &lt;enumeration value="imk"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "_CountryIdentificationSchemeType")
@XmlEnum
public enum CountryIdentificationSchemeType {


    /**
     * Dette format følge ISO 3166 standarden, alpha 2.
     * 
     */
    @XmlEnumValue("iso3166-alpha2")
    ISO_3166_ALPHA_2("iso3166-alpha2"),

    /**
     * Dette format følge ISO 3166 standarden, alpha 3.
     * 
     */
    @XmlEnumValue("iso3166-alpha3")
    ISO_3166_ALPHA_3("iso3166-alpha3"),

    /**
     * Dette format følger FNs Statistik Kontor landekoder
     * 
     */
    @XmlEnumValue("un-numeric3")
    UN_NUMERIC_3("un-numeric3"),

    /**
     * Dette format følger MyndighedsKoden fra Det Centrale Personregister
     * 
     */
    @XmlEnumValue("imk")
    IMK("imk");
    private final String value;

    CountryIdentificationSchemeType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static CountryIdentificationSchemeType fromValue(String v) {
        for (CountryIdentificationSchemeType c: CountryIdentificationSchemeType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
