//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.06.14 at 09:30:07 AM CEST
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://rep.oio.dk/xkom.dk/xml/schemas/2005/03/15/", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package dk.oio.rep.xkom_dk.xml.schemas._2005._03._15;
