//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.3u2-hudson-jaxb-ri-2.2.3-4- 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.05.25 at 09:38:22 AM CEST 
//


package oio.sagdok.person._1_0;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for AdresseType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="AdresseType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;choice>
 *         &lt;element ref="{urn:oio:sagdok:person:1.0.0}DanskAdresse"/>
 *         &lt;element ref="{urn:oio:sagdok:person:1.0.0}GroenlandAdresse"/>
 *         &lt;element ref="{urn:oio:sagdok:person:1.0.0}VerdenAdresse"/>
 *       &lt;/choice>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "AdresseType", propOrder = {
    "danskAdresse",
    "groenlandAdresse",
    "verdenAdresse"
})
public class AdresseType {

    @XmlElement(name = "DanskAdresse")
    protected DanskAdresseType danskAdresse;
    @XmlElement(name = "GroenlandAdresse")
    protected GroenlandAdresseType groenlandAdresse;
    @XmlElement(name = "VerdenAdresse")
    protected VerdenAdresseType verdenAdresse;

    /**
     * Gets the value of the danskAdresse property.
     * 
     * @return
     *     possible object is
     *     {@link DanskAdresseType }
     *     
     */
    public DanskAdresseType getDanskAdresse() {
        return danskAdresse;
    }

    /**
     * Sets the value of the danskAdresse property.
     * 
     * @param value
     *     allowed object is
     *     {@link DanskAdresseType }
     *     
     */
    public void setDanskAdresse(DanskAdresseType value) {
        this.danskAdresse = value;
    }

    /**
     * Gets the value of the groenlandAdresse property.
     * 
     * @return
     *     possible object is
     *     {@link GroenlandAdresseType }
     *     
     */
    public GroenlandAdresseType getGroenlandAdresse() {
        return groenlandAdresse;
    }

    /**
     * Sets the value of the groenlandAdresse property.
     * 
     * @param value
     *     allowed object is
     *     {@link GroenlandAdresseType }
     *     
     */
    public void setGroenlandAdresse(GroenlandAdresseType value) {
        this.groenlandAdresse = value;
    }

    /**
     * Gets the value of the verdenAdresse property.
     * 
     * @return
     *     possible object is
     *     {@link VerdenAdresseType }
     *     
     */
    public VerdenAdresseType getVerdenAdresse() {
        return verdenAdresse;
    }

    /**
     * Sets the value of the verdenAdresse property.
     * 
     * @param value
     *     allowed object is
     *     {@link VerdenAdresseType }
     *     
     */
    public void setVerdenAdresse(VerdenAdresseType value) {
        this.verdenAdresse = value;
    }

}
