//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.06.14 at 09:30:07 AM CEST
//


package oio.sagdok.person._1_0;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import dk.oio.rep.ebxml.xml.schemas.dkcc._2003._02._13.CountryIdentificationCodeType;


/**
 * <p>Java class for CprBorgerType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="CprBorgerType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://rep.oio.dk/cpr.dk/xml/schemas/core/2005/03/18/}PersonCivilRegistrationIdentifier"/>
 *         &lt;element ref="{urn:oio:sagdok:person:1.0.0}PersonNummerGyldighedStatusIndikator"/>
 *         &lt;element ref="{http://rep.oio.dk/ebxml/xml/schemas/dkcc/2006/01/03/}PersonNationalityCode"/>
 *         &lt;element ref="{urn:oio:sagdok:person:1.0.0}FolkeregisterAdresse" minOccurs="0"/>
 *         &lt;element ref="{urn:oio:sagdok:person:1.0.0}NavneAdresseBeskyttelseIndikator"/>
 *         &lt;element ref="{urn:oio:sagdok:person:1.0.0}TelefonNummerBeskyttelseIndikator"/>
 *         &lt;element ref="{urn:oio:sagdok:person:1.0.0}ForskerBeskyttelseIndikator"/>
 *         &lt;element ref="{urn:oio:sagdok:person:1.0.0}AdresseNoteTekst" minOccurs="0"/>
 *         &lt;element ref="{urn:oio:sagdok:person:1.0.0}FolkekirkeMedlemIndikator" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "CprBorgerType", propOrder = {
    "personCivilRegistrationIdentifier",
    "personNummerGyldighedStatusIndikator",
    "personNationalityCode",
    "folkeregisterAdresse",
    "navneAdresseBeskyttelseIndikator",
    "telefonNummerBeskyttelseIndikator",
    "forskerBeskyttelseIndikator",
    "adresseNoteTekst",
    "folkekirkeMedlemIndikator"
})
public class CprBorgerType {

    @XmlElement(name = "PersonCivilRegistrationIdentifier", namespace = "http://rep.oio.dk/cpr.dk/xml/schemas/core/2005/03/18/", required = true)
    protected String personCivilRegistrationIdentifier;
    @XmlElement(name = "PersonNummerGyldighedStatusIndikator")
    protected boolean personNummerGyldighedStatusIndikator;
    @XmlElement(name = "PersonNationalityCode", namespace = "http://rep.oio.dk/ebxml/xml/schemas/dkcc/2006/01/03/", required = true)
    protected CountryIdentificationCodeType personNationalityCode;
    @XmlElement(name = "FolkeregisterAdresse")
    protected AdresseType folkeregisterAdresse;
    @XmlElement(name = "NavneAdresseBeskyttelseIndikator")
    protected boolean navneAdresseBeskyttelseIndikator;
    @XmlElement(name = "TelefonNummerBeskyttelseIndikator")
    protected boolean telefonNummerBeskyttelseIndikator;
    @XmlElement(name = "ForskerBeskyttelseIndikator")
    protected boolean forskerBeskyttelseIndikator;
    @XmlElement(name = "AdresseNoteTekst")
    protected String adresseNoteTekst;
    @XmlElement(name = "FolkekirkeMedlemIndikator")
    protected Boolean folkekirkeMedlemIndikator;

    /**
     * Gets the value of the personCivilRegistrationIdentifier property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPersonCivilRegistrationIdentifier() {
        return personCivilRegistrationIdentifier;
    }

    /**
     * Sets the value of the personCivilRegistrationIdentifier property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPersonCivilRegistrationIdentifier(String value) {
        this.personCivilRegistrationIdentifier = value;
    }

    /**
     * Gets the value of the personNummerGyldighedStatusIndikator property.
     * 
     */
    public boolean isPersonNummerGyldighedStatusIndikator() {
        return personNummerGyldighedStatusIndikator;
    }

    /**
     * Sets the value of the personNummerGyldighedStatusIndikator property.
     * 
     */
    public void setPersonNummerGyldighedStatusIndikator(boolean value) {
        this.personNummerGyldighedStatusIndikator = value;
    }

    /**
     * Gets the value of the personNationalityCode property.
     * 
     * @return
     *     possible object is
     *     {@link CountryIdentificationCodeType }
     *     
     */
    public CountryIdentificationCodeType getPersonNationalityCode() {
        return personNationalityCode;
    }

    /**
     * Sets the value of the personNationalityCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link CountryIdentificationCodeType }
     *     
     */
    public void setPersonNationalityCode(CountryIdentificationCodeType value) {
        this.personNationalityCode = value;
    }

    /**
     * Gets the value of the folkeregisterAdresse property.
     *
     * @return
     *     possible object is
     *     {@link AdresseType }
     *
     */
    public AdresseType getFolkeregisterAdresse() {
        return folkeregisterAdresse;
    }

    /**
     * Sets the value of the folkeregisterAdresse property.
     *
     * @param value
     *     allowed object is
     *     {@link AdresseType }
     *
     */
    public void setFolkeregisterAdresse(AdresseType value) {
        this.folkeregisterAdresse = value;
    }

    /**
     * Gets the value of the navneAdresseBeskyttelseIndikator property.
     * 
     */
    public boolean isNavneAdresseBeskyttelseIndikator() {
        return navneAdresseBeskyttelseIndikator;
    }

    /**
     * Sets the value of the navneAdresseBeskyttelseIndikator property.
     * 
     */
    public void setNavneAdresseBeskyttelseIndikator(boolean value) {
        this.navneAdresseBeskyttelseIndikator = value;
    }

    /**
     * Gets the value of the telefonNummerBeskyttelseIndikator property.
     * 
     */
    public boolean isTelefonNummerBeskyttelseIndikator() {
        return telefonNummerBeskyttelseIndikator;
    }

    /**
     * Sets the value of the telefonNummerBeskyttelseIndikator property.
     * 
     */
    public void setTelefonNummerBeskyttelseIndikator(boolean value) {
        this.telefonNummerBeskyttelseIndikator = value;
    }

    /**
     * Gets the value of the forskerBeskyttelseIndikator property.
     * 
     */
    public boolean isForskerBeskyttelseIndikator() {
        return forskerBeskyttelseIndikator;
    }

    /**
     * Sets the value of the forskerBeskyttelseIndikator property.
     * 
     */
    public void setForskerBeskyttelseIndikator(boolean value) {
        this.forskerBeskyttelseIndikator = value;
    }

    /**
     * Gets the value of the adresseNoteTekst property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAdresseNoteTekst() {
        return adresseNoteTekst;
    }

    /**
     * Sets the value of the adresseNoteTekst property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAdresseNoteTekst(String value) {
        this.adresseNoteTekst = value;
    }

    /**
     * Gets the value of the folkekirkeMedlemIndikator property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *
     */
    public Boolean isFolkekirkeMedlemIndikator() {
        return folkekirkeMedlemIndikator;
    }

    /**
     * Sets the value of the folkekirkeMedlemIndikator property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *
     */
    public void setFolkekirkeMedlemIndikator(Boolean value) {
        this.folkekirkeMedlemIndikator = value;
    }

}
