//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.06.14 at 09:30:07 AM CEST
//


package oio.sagdok.person._1_0;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;
import dk.oio.rep.ebxml.xml.schemas.dkcc._2006._01._23.PersonGenderCodeType;
import oio.sagdok._3_0.VirkningType;


/**
 * <p>Java class for EgenskabType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="EgenskabType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{urn:oio:sagdok:3.0.0}BrugervendtNoegleTekst" minOccurs="0"/>
 *         &lt;element ref="{urn:oio:sagdok:person:1.0.0}NavnStruktur" minOccurs="0"/>
 *         &lt;element ref="{http://rep.oio.dk/ebxml/xml/schemas/dkcc/2006/01/23/}PersonGenderCode" minOccurs="0"/>
 *         &lt;element ref="{http://rep.oio.dk/ebxml/xml/schemas/dkcc/2005/03/15/}BirthDate" minOccurs="0"/>
 *         &lt;element ref="{urn:oio:sagdok:person:1.0.0}FoedselsregistreringMyndighedNavn" minOccurs="0"/>
 *         &lt;element ref="{urn:oio:sagdok:person:1.0.0}FoedestedNavn" minOccurs="0"/>
 *         &lt;element ref="{urn:oio:sagdok:person:1.0.0}AndenAdresse" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element ref="{urn:oio:sagdok:person:1.0.0}KontaktKanal" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element ref="{urn:oio:sagdok:person:1.0.0}NaermestePaaroerende" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element ref="{urn:oio:sagdok:3.0.0}Virkning" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "EgenskabType", propOrder = {
    "brugervendtNoegleTekst",
    "navnStruktur",
    "personGenderCode",
    "birthDate",
    "foedselsregistreringMyndighedNavn",
    "foedestedNavn",
    "andenAdresse",
    "kontaktKanal",
    "naermestePaaroerende",
    "virkning"
})
public class EgenskabType {

    @XmlElement(name = "BrugervendtNoegleTekst", namespace = "urn:oio:sagdok:3.0.0")
    protected String brugervendtNoegleTekst;
    @XmlElement(name = "NavnStruktur")
    protected NavnStrukturType navnStruktur;
    @XmlElement(name = "PersonGenderCode", namespace = "http://rep.oio.dk/ebxml/xml/schemas/dkcc/2006/01/23/")
    protected PersonGenderCodeType personGenderCode;
    @XmlElement(name = "BirthDate", namespace = "http://rep.oio.dk/ebxml/xml/schemas/dkcc/2005/03/15/")
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar birthDate;
    @XmlElement(name = "FoedselsregistreringMyndighedNavn")
    protected String foedselsregistreringMyndighedNavn;
    @XmlElement(name = "FoedestedNavn")
    protected String foedestedNavn;
    @XmlElement(name = "AndenAdresse")
    protected List<AdresseType> andenAdresse;
    @XmlElement(name = "KontaktKanal")
    protected List<KontaktKanalType> kontaktKanal;
    @XmlElement(name = "NaermestePaaroerende")
    protected List<KontaktKanalType> naermestePaaroerende;
    @XmlElement(name = "Virkning", namespace = "urn:oio:sagdok:3.0.0")
    protected VirkningType virkning;

    /**
     * Gets the value of the brugervendtNoegleTekst property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getBrugervendtNoegleTekst() {
        return brugervendtNoegleTekst;
    }

    /**
     * Sets the value of the brugervendtNoegleTekst property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setBrugervendtNoegleTekst(String value) {
        this.brugervendtNoegleTekst = value;
    }

    /**
     * Gets the value of the navnStruktur property.
     * 
     * @return
     *     possible object is
     *     {@link NavnStrukturType }
     *     
     */
    public NavnStrukturType getNavnStruktur() {
        return navnStruktur;
    }

    /**
     * Sets the value of the navnStruktur property.
     * 
     * @param value
     *     allowed object is
     *     {@link NavnStrukturType }
     *     
     */
    public void setNavnStruktur(NavnStrukturType value) {
        this.navnStruktur = value;
    }

    /**
     * Gets the value of the personGenderCode property.
     * 
     * @return
     *     possible object is
     *     {@link PersonGenderCodeType }
     *     
     */
    public PersonGenderCodeType getPersonGenderCode() {
        return personGenderCode;
    }

    /**
     * Sets the value of the personGenderCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link PersonGenderCodeType }
     *     
     */
    public void setPersonGenderCode(PersonGenderCodeType value) {
        this.personGenderCode = value;
    }

    /**
     * Gets the value of the birthDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getBirthDate() {
        return birthDate;
    }

    /**
     * Sets the value of the birthDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setBirthDate(XMLGregorianCalendar value) {
        this.birthDate = value;
    }

    /**
     * Gets the value of the foedselsregistreringMyndighedNavn property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFoedselsregistreringMyndighedNavn() {
        return foedselsregistreringMyndighedNavn;
    }

    /**
     * Sets the value of the foedselsregistreringMyndighedNavn property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFoedselsregistreringMyndighedNavn(String value) {
        this.foedselsregistreringMyndighedNavn = value;
    }

    /**
     * Gets the value of the foedestedNavn property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFoedestedNavn() {
        return foedestedNavn;
    }

    /**
     * Sets the value of the foedestedNavn property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFoedestedNavn(String value) {
        this.foedestedNavn = value;
    }

    /**
     * Gets the value of the andenAdresse property.
     *
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the andenAdresse property.
     *
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getAndenAdresse().add(newItem);
     * </pre>
     *
     *
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link AdresseType }
     *
     * 
     */
    public List<AdresseType> getAndenAdresse() {
        if (andenAdresse == null) {
            andenAdresse = new ArrayList<AdresseType>();
        }
        return this.andenAdresse;
    }

    /**
     * Gets the value of the kontaktKanal property.
     *
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the kontaktKanal property.
     *
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getKontaktKanal().add(newItem);
     * </pre>
     *
     *
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link KontaktKanalType }
     *
     * 
     */
    public List<KontaktKanalType> getKontaktKanal() {
        if (kontaktKanal == null) {
            kontaktKanal = new ArrayList<KontaktKanalType>();
        }
        return this.kontaktKanal;
    }

    /**
     * Gets the value of the naermestePaaroerende property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the naermestePaaroerende property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getNaermestePaaroerende().add(newItem);
     * </pre>
     *
     *
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link KontaktKanalType }
     * 
     * 
     */
    public List<KontaktKanalType> getNaermestePaaroerende() {
        if (naermestePaaroerende == null) {
            naermestePaaroerende = new ArrayList<KontaktKanalType>();
        }
        return this.naermestePaaroerende;
    }

    /**
     * Gets the value of the virkning property.
     * 
     * @return
     *     possible object is
     *     {@link VirkningType }
     *     
     */
    public VirkningType getVirkning() {
        return virkning;
    }

    /**
     * Sets the value of the virkning property.
     * 
     * @param value
     *     allowed object is
     *     {@link VirkningType }
     *     
     */
    public void setVirkning(VirkningType value) {
        this.virkning = value;
    }

}
