//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.3u2-hudson-jaxb-ri-2.2.3-4- 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.05.25 at 09:38:22 AM CEST 
//


package oio.sagdok.person._1_0;

import java.math.BigInteger;
import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;
import dk.oio.rep.ebxml.xml.schemas.dkcc._2003._02._13.CountryIdentificationCodeType;
import oio.sagdok._2_0.PersonFlerRelationType;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the oio.sagdok.person._1_0 package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _PraktiserendeLaegeYderNummerIdentifikator_QNAME = new QName("urn:oio:sagdok:person:1.0.0", "PraktiserendeLaegeYderNummerIdentifikator");
    private final static QName _SpecielVejkodeIndikator_QNAME = new QName("urn:oio:sagdok:person:1.0.0", "SpecielVejkodeIndikator");
    private final static QName _VerdenAdresse_QNAME = new QName("urn:oio:sagdok:person:1.0.0", "VerdenAdresse");
    private final static QName _SygesikringsgruppeKode_QNAME = new QName("urn:oio:sagdok:person:1.0.0", "SygesikringsgruppeKode");
    private final static QName _Foraeldremyndighedsindehaver_QNAME = new QName("urn:oio:sagdok:person:1.0.0", "Foraeldremyndighedsindehaver");
    private final static QName _UkendtAdresseIndikator_QNAME = new QName("urn:oio:sagdok:person:1.0.0", "UkendtAdresseIndikator");
    private final static QName _Fader_QNAME = new QName("urn:oio:sagdok:person:1.0.0", "Fader");
    private final static QName _SogneDistriktTekst_QNAME = new QName("urn:oio:sagdok:person:1.0.0", "SogneDistriktTekst");
    private final static QName _RelationListe_QNAME = new QName("urn:oio:sagdok:person:1.0.0", "RelationListe");
    private final static QName _FoedselsregistreringMyndighedNavn_QNAME = new QName("urn:oio:sagdok:person:1.0.0", "FoedselsregistreringMyndighedNavn");
    private final static QName _AdresseNoteTekst_QNAME = new QName("urn:oio:sagdok:person:1.0.0", "AdresseNoteTekst");
    private final static QName _LivStatusKode_QNAME = new QName("urn:oio:sagdok:person:1.0.0", "LivStatusKode");
    private final static QName _PersonNummerGyldighedStatusIndikator_QNAME = new QName("urn:oio:sagdok:person:1.0.0", "PersonNummerGyldighedStatusIndikator");
    private final static QName _PersonRelation_QNAME = new QName("urn:oio:sagdok:person:1.0.0", "PersonRelation");
    private final static QName _SkoleDistriktTekst_QNAME = new QName("urn:oio:sagdok:person:1.0.0", "SkoleDistriktTekst");
    private final static QName _FoedestedNavn_QNAME = new QName("urn:oio:sagdok:person:1.0.0", "FoedestedNavn");
    private final static QName _ErstatningAf_QNAME = new QName("urn:oio:sagdok:person:1.0.0", "ErstatningAf");
    private final static QName _PraktiserendeLaegeNavn_QNAME = new QName("urn:oio:sagdok:person:1.0.0", "PraktiserendeLaegeNavn");
    private final static QName _KontaktKanal_QNAME = new QName("urn:oio:sagdok:person:1.0.0", "KontaktKanal");
    private final static QName _FolkeregisterAdresse_QNAME = new QName("urn:oio:sagdok:person:1.0.0", "FolkeregisterAdresse");
    private final static QName _ForskerBeskyttelseIndikator_QNAME = new QName("urn:oio:sagdok:person:1.0.0", "ForskerBeskyttelseIndikator");
    private final static QName _TilstandListe_QNAME = new QName("urn:oio:sagdok:person:1.0.0", "TilstandListe");
    private final static QName _RetligHandleevneVaergeForPersonen_QNAME = new QName("urn:oio:sagdok:person:1.0.0", "RetligHandleevneVaergeForPersonen");
    private final static QName _Boern_QNAME = new QName("urn:oio:sagdok:person:1.0.0", "Boern");
    private final static QName _AttributListe_QNAME = new QName("urn:oio:sagdok:person:1.0.0", "AttributListe");
    private final static QName _Telefon_QNAME = new QName("urn:oio:sagdok:person:1.0.0", "Telefon");
    private final static QName _SundhedOplysning_QNAME = new QName("urn:oio:sagdok:person:1.0.0", "SundhedOplysning");
    private final static QName _Adresse_QNAME = new QName("urn:oio:sagdok:person:1.0.0", "Adresse");
    private final static QName _RegistreretPartner_QNAME = new QName("urn:oio:sagdok:person:1.0.0", "RegistreretPartner");
    private final static QName _FolkekirkeMedlemIndikator_QNAME = new QName("urn:oio:sagdok:person:1.0.0", "FolkekirkeMedlemIndikator");
    private final static QName _RegisterOplysningBase_QNAME = new QName("urn:oio:sagdok:person:1.0.0", "RegisterOplysningBase");
    private final static QName _TelefonNummerBeskyttelseIndikator_QNAME = new QName("urn:oio:sagdok:person:1.0.0", "TelefonNummerBeskyttelseIndikator");
    private final static QName _Egenskab_QNAME = new QName("urn:oio:sagdok:person:1.0.0", "Egenskab");
    private final static QName _CivilStatus_QNAME = new QName("urn:oio:sagdok:person:1.0.0", "CivilStatus");
    private final static QName _Bopaelssamling_QNAME = new QName("urn:oio:sagdok:person:1.0.0", "Bopaelssamling");
    private final static QName _NavnStruktur_QNAME = new QName("urn:oio:sagdok:person:1.0.0", "NavnStruktur");
    private final static QName _KontaktKanalTekst_QNAME = new QName("urn:oio:sagdok:person:1.0.0", "KontaktKanalTekst");
    private final static QName _LivStatus_QNAME = new QName("urn:oio:sagdok:person:1.0.0", "LivStatus");
    private final static QName _Moder_QNAME = new QName("urn:oio:sagdok:person:1.0.0", "Moder");
    private final static QName _ErstatningFor_QNAME = new QName("urn:oio:sagdok:person:1.0.0", "ErstatningFor");
    private final static QName _Foraeldremyndighedsboern_QNAME = new QName("urn:oio:sagdok:person:1.0.0", "Foraeldremyndighedsboern");
    private final static QName _Aegtefaelle_QNAME = new QName("urn:oio:sagdok:person:1.0.0", "Aegtefaelle");
    private final static QName _PersonIdentifikator_QNAME = new QName("urn:oio:sagdok:person:1.0.0", "PersonIdentifikator");
    private final static QName _BegraensetAnvendelseTekst_QNAME = new QName("urn:oio:sagdok:person:1.0.0", "BegraensetAnvendelseTekst");
    private final static QName _UdenlandskBorger_QNAME = new QName("urn:oio:sagdok:person:1.0.0", "UdenlandskBorger");
    private final static QName _AndreAdresser_QNAME = new QName("urn:oio:sagdok:person:1.0.0", "AndreAdresser");
    private final static QName _PostDistriktTekst_QNAME = new QName("urn:oio:sagdok:person:1.0.0", "PostDistriktTekst");
    private final static QName _DanskAdresse_QNAME = new QName("urn:oio:sagdok:person:1.0.0", "DanskAdresse");
    private final static QName _ValgkredsDistriktTekst_QNAME = new QName("urn:oio:sagdok:person:1.0.0", "ValgkredsDistriktTekst");
    private final static QName _SocialDistriktTekst_QNAME = new QName("urn:oio:sagdok:person:1.0.0", "SocialDistriktTekst");
    private final static QName _RetligHandleevneVaergemaalsindehaver_QNAME = new QName("urn:oio:sagdok:person:1.0.0", "RetligHandleevneVaergemaalsindehaver");
    private final static QName _RegisterOplysning_QNAME = new QName("urn:oio:sagdok:person:1.0.0", "RegisterOplysning");
    private final static QName _UkendtBorger_QNAME = new QName("urn:oio:sagdok:person:1.0.0", "UkendtBorger");
    private final static QName _FoedselslandKode_QNAME = new QName("urn:oio:sagdok:person:1.0.0", "FoedselslandKode");
    private final static QName _PolitiDistriktTekst_QNAME = new QName("urn:oio:sagdok:person:1.0.0", "PolitiDistriktTekst");
    private final static QName _GroenlandAdresse_QNAME = new QName("urn:oio:sagdok:person:1.0.0", "GroenlandAdresse");
    private final static QName _NavneAdresseBeskyttelseIndikator_QNAME = new QName("urn:oio:sagdok:person:1.0.0", "NavneAdresseBeskyttelseIndikator");
    private final static QName _SprogKode_QNAME = new QName("urn:oio:sagdok:person:1.0.0", "SprogKode");
    private final static QName _NaermestePaaroerende_QNAME = new QName("urn:oio:sagdok:person:1.0.0", "NaermestePaaroerende");
    private final static QName _AndenKontaktKanal_QNAME = new QName("urn:oio:sagdok:person:1.0.0", "AndenKontaktKanal");
    private final static QName _KanBrugesTilSmsIndikator_QNAME = new QName("urn:oio:sagdok:person:1.0.0", "KanBrugesTilSmsIndikator");
    private final static QName _KontaktKanalBase_QNAME = new QName("urn:oio:sagdok:person:1.0.0", "KontaktKanalBase");
    private final static QName _Registrering_QNAME = new QName("urn:oio:sagdok:person:1.0.0", "Registrering");
    private final static QName _CprBorger_QNAME = new QName("urn:oio:sagdok:person:1.0.0", "CprBorger");
    private final static QName _CivilStatusKode_QNAME = new QName("urn:oio:sagdok:person:1.0.0", "CivilStatusKode");
    private final static QName _Person_QNAME = new QName("urn:oio:sagdok:person:1.0.0", "Person");
    private final static QName _AdresseBase_QNAME = new QName("urn:oio:sagdok:person:1.0.0", "AdresseBase");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: oio.sagdok.person._1_0
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link NavnStrukturType }
     * 
     */
    public NavnStrukturType createNavnStrukturType() {
        return new NavnStrukturType();
    }

    /**
     * Create an instance of {@link PersonRelationType }
     * 
     */
    public PersonRelationType createPersonRelationType() {
        return new PersonRelationType();
    }

    /**
     * Create an instance of {@link LivStatusType }
     * 
     */
    public LivStatusType createLivStatusType() {
        return new LivStatusType();
    }

    /**
     * Create an instance of {@link VerdenAdresseType }
     * 
     */
    public VerdenAdresseType createVerdenAdresseType() {
        return new VerdenAdresseType();
    }

    /**
     * Create an instance of {@link AdresseType }
     * 
     */
    public AdresseType createAdresseType() {
        return new AdresseType();
    }

    /**
     * Create an instance of {@link UdenlandskBorgerType }
     * 
     */
    public UdenlandskBorgerType createUdenlandskBorgerType() {
        return new UdenlandskBorgerType();
    }

    /**
     * Create an instance of {@link DanskAdresseType }
     * 
     */
    public DanskAdresseType createDanskAdresseType() {
        return new DanskAdresseType();
    }

    /**
     * Create an instance of {@link RelationListeType }
     * 
     */
    public RelationListeType createRelationListeType() {
        return new RelationListeType();
    }

    /**
     * Create an instance of {@link RegisterOplysningType }
     * 
     */
    public RegisterOplysningType createRegisterOplysningType() {
        return new RegisterOplysningType();
    }

    /**
     * Create an instance of {@link UkendtBorgerType }
     * 
     */
    public UkendtBorgerType createUkendtBorgerType() {
        return new UkendtBorgerType();
    }

    /**
     * Create an instance of {@link GroenlandAdresseType }
     * 
     */
    public GroenlandAdresseType createGroenlandAdresseType() {
        return new GroenlandAdresseType();
    }

    /**
     * Create an instance of {@link KontaktKanalType }
     * 
     */
    public KontaktKanalType createKontaktKanalType() {
        return new KontaktKanalType();
    }

    /**
     * Create an instance of {@link AndenKontaktKanalType }
     * 
     */
    public AndenKontaktKanalType createAndenKontaktKanalType() {
        return new AndenKontaktKanalType();
    }

    /**
     * Create an instance of {@link AttributListeType }
     * 
     */
    public AttributListeType createAttributListeType() {
        return new AttributListeType();
    }

    /**
     * Create an instance of {@link TilstandListeType }
     * 
     */
    public TilstandListeType createTilstandListeType() {
        return new TilstandListeType();
    }

    /**
     * Create an instance of {@link KontaktKanalBaseType }
     * 
     */
    public KontaktKanalBaseType createKontaktKanalBaseType() {
        return new KontaktKanalBaseType();
    }

    /**
     * Create an instance of {@link TelefonType }
     * 
     */
    public TelefonType createTelefonType() {
        return new TelefonType();
    }

    /**
     * Create an instance of {@link SundhedOplysningType }
     * 
     */
    public SundhedOplysningType createSundhedOplysningType() {
        return new SundhedOplysningType();
    }

    /**
     * Create an instance of {@link RegistreringType }
     * 
     */
    public RegistreringType createRegistreringType() {
        return new RegistreringType();
    }

    /**
     * Create an instance of {@link CprBorgerType }
     * 
     */
    public CprBorgerType createCprBorgerType() {
        return new CprBorgerType();
    }

    /**
     * Create an instance of {@link RegisterOplysningBaseType }
     * 
     */
    public RegisterOplysningBaseType createRegisterOplysningBaseType() {
        return new RegisterOplysningBaseType();
    }

    /**
     * Create an instance of {@link AdresseBaseType }
     * 
     */
    public AdresseBaseType createAdresseBaseType() {
        return new AdresseBaseType();
    }

    /**
     * Create an instance of {@link CivilStatusType }
     * 
     */
    public CivilStatusType createCivilStatusType() {
        return new CivilStatusType();
    }

    /**
     * Create an instance of {@link PersonType }
     * 
     */
    public PersonType createPersonType() {
        return new PersonType();
    }

    /**
     * Create an instance of {@link EgenskabType }
     * 
     */
    public EgenskabType createEgenskabType() {
        return new EgenskabType();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:oio:sagdok:person:1.0.0", name = "PraktiserendeLaegeYderNummerIdentifikator")
    public JAXBElement<BigInteger> createPraktiserendeLaegeYderNummerIdentifikator(BigInteger value) {
        return new JAXBElement<BigInteger>(_PraktiserendeLaegeYderNummerIdentifikator_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Boolean }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:oio:sagdok:person:1.0.0", name = "SpecielVejkodeIndikator")
    public JAXBElement<Boolean> createSpecielVejkodeIndikator(Boolean value) {
        return new JAXBElement<Boolean>(_SpecielVejkodeIndikator_QNAME, Boolean.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link VerdenAdresseType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:oio:sagdok:person:1.0.0", name = "VerdenAdresse")
    public JAXBElement<VerdenAdresseType> createVerdenAdresse(VerdenAdresseType value) {
        return new JAXBElement<VerdenAdresseType>(_VerdenAdresse_QNAME, VerdenAdresseType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:oio:sagdok:person:1.0.0", name = "SygesikringsgruppeKode")
    public JAXBElement<BigInteger> createSygesikringsgruppeKode(BigInteger value) {
        return new JAXBElement<BigInteger>(_SygesikringsgruppeKode_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link PersonRelationType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:oio:sagdok:person:1.0.0", name = "Foraeldremyndighedsindehaver")
    public JAXBElement<PersonRelationType> createForaeldremyndighedsindehaver(PersonRelationType value) {
        return new JAXBElement<PersonRelationType>(_Foraeldremyndighedsindehaver_QNAME, PersonRelationType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Boolean }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:oio:sagdok:person:1.0.0", name = "UkendtAdresseIndikator")
    public JAXBElement<Boolean> createUkendtAdresseIndikator(Boolean value) {
        return new JAXBElement<Boolean>(_UkendtAdresseIndikator_QNAME, Boolean.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link PersonRelationType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:oio:sagdok:person:1.0.0", name = "Fader")
    public JAXBElement<PersonRelationType> createFader(PersonRelationType value) {
        return new JAXBElement<PersonRelationType>(_Fader_QNAME, PersonRelationType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:oio:sagdok:person:1.0.0", name = "SogneDistriktTekst")
    public JAXBElement<String> createSogneDistriktTekst(String value) {
        return new JAXBElement<String>(_SogneDistriktTekst_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link RelationListeType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:oio:sagdok:person:1.0.0", name = "RelationListe")
    public JAXBElement<RelationListeType> createRelationListe(RelationListeType value) {
        return new JAXBElement<RelationListeType>(_RelationListe_QNAME, RelationListeType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:oio:sagdok:person:1.0.0", name = "FoedselsregistreringMyndighedNavn")
    public JAXBElement<String> createFoedselsregistreringMyndighedNavn(String value) {
        return new JAXBElement<String>(_FoedselsregistreringMyndighedNavn_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:oio:sagdok:person:1.0.0", name = "AdresseNoteTekst")
    public JAXBElement<String> createAdresseNoteTekst(String value) {
        return new JAXBElement<String>(_AdresseNoteTekst_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link LivStatusKodeType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:oio:sagdok:person:1.0.0", name = "LivStatusKode")
    public JAXBElement<LivStatusKodeType> createLivStatusKode(LivStatusKodeType value) {
        return new JAXBElement<LivStatusKodeType>(_LivStatusKode_QNAME, LivStatusKodeType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Boolean }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:oio:sagdok:person:1.0.0", name = "PersonNummerGyldighedStatusIndikator")
    public JAXBElement<Boolean> createPersonNummerGyldighedStatusIndikator(Boolean value) {
        return new JAXBElement<Boolean>(_PersonNummerGyldighedStatusIndikator_QNAME, Boolean.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link PersonRelationType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:oio:sagdok:person:1.0.0", name = "PersonRelation")
    public JAXBElement<PersonRelationType> createPersonRelation(PersonRelationType value) {
        return new JAXBElement<PersonRelationType>(_PersonRelation_QNAME, PersonRelationType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:oio:sagdok:person:1.0.0", name = "SkoleDistriktTekst")
    public JAXBElement<String> createSkoleDistriktTekst(String value) {
        return new JAXBElement<String>(_SkoleDistriktTekst_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:oio:sagdok:person:1.0.0", name = "FoedestedNavn")
    public JAXBElement<String> createFoedestedNavn(String value) {
        return new JAXBElement<String>(_FoedestedNavn_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link PersonRelationType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:oio:sagdok:person:1.0.0", name = "ErstatningAf")
    public JAXBElement<PersonRelationType> createErstatningAf(PersonRelationType value) {
        return new JAXBElement<PersonRelationType>(_ErstatningAf_QNAME, PersonRelationType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:oio:sagdok:person:1.0.0", name = "PraktiserendeLaegeNavn")
    public JAXBElement<String> createPraktiserendeLaegeNavn(String value) {
        return new JAXBElement<String>(_PraktiserendeLaegeNavn_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link KontaktKanalType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:oio:sagdok:person:1.0.0", name = "KontaktKanal")
    public JAXBElement<KontaktKanalType> createKontaktKanal(KontaktKanalType value) {
        return new JAXBElement<KontaktKanalType>(_KontaktKanal_QNAME, KontaktKanalType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link AdresseType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:oio:sagdok:person:1.0.0", name = "FolkeregisterAdresse")
    public JAXBElement<AdresseType> createFolkeregisterAdresse(AdresseType value) {
        return new JAXBElement<AdresseType>(_FolkeregisterAdresse_QNAME, AdresseType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Boolean }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:oio:sagdok:person:1.0.0", name = "ForskerBeskyttelseIndikator")
    public JAXBElement<Boolean> createForskerBeskyttelseIndikator(Boolean value) {
        return new JAXBElement<Boolean>(_ForskerBeskyttelseIndikator_QNAME, Boolean.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TilstandListeType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:oio:sagdok:person:1.0.0", name = "TilstandListe")
    public JAXBElement<TilstandListeType> createTilstandListe(TilstandListeType value) {
        return new JAXBElement<TilstandListeType>(_TilstandListe_QNAME, TilstandListeType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link PersonRelationType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:oio:sagdok:person:1.0.0", name = "RetligHandleevneVaergeForPersonen")
    public JAXBElement<PersonRelationType> createRetligHandleevneVaergeForPersonen(PersonRelationType value) {
        return new JAXBElement<PersonRelationType>(_RetligHandleevneVaergeForPersonen_QNAME, PersonRelationType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link PersonFlerRelationType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:oio:sagdok:person:1.0.0", name = "Boern")
    public JAXBElement<PersonFlerRelationType> createBoern(PersonFlerRelationType value) {
        return new JAXBElement<PersonFlerRelationType>(_Boern_QNAME, PersonFlerRelationType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link AttributListeType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:oio:sagdok:person:1.0.0", name = "AttributListe")
    public JAXBElement<AttributListeType> createAttributListe(AttributListeType value) {
        return new JAXBElement<AttributListeType>(_AttributListe_QNAME, AttributListeType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TelefonType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:oio:sagdok:person:1.0.0", name = "Telefon")
    public JAXBElement<TelefonType> createTelefon(TelefonType value) {
        return new JAXBElement<TelefonType>(_Telefon_QNAME, TelefonType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link SundhedOplysningType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:oio:sagdok:person:1.0.0", name = "SundhedOplysning")
    public JAXBElement<SundhedOplysningType> createSundhedOplysning(SundhedOplysningType value) {
        return new JAXBElement<SundhedOplysningType>(_SundhedOplysning_QNAME, SundhedOplysningType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link AdresseType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:oio:sagdok:person:1.0.0", name = "Adresse")
    public JAXBElement<AdresseType> createAdresse(AdresseType value) {
        return new JAXBElement<AdresseType>(_Adresse_QNAME, AdresseType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link PersonRelationType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:oio:sagdok:person:1.0.0", name = "RegistreretPartner")
    public JAXBElement<PersonRelationType> createRegistreretPartner(PersonRelationType value) {
        return new JAXBElement<PersonRelationType>(_RegistreretPartner_QNAME, PersonRelationType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Boolean }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:oio:sagdok:person:1.0.0", name = "FolkekirkeMedlemIndikator")
    public JAXBElement<Boolean> createFolkekirkeMedlemIndikator(Boolean value) {
        return new JAXBElement<Boolean>(_FolkekirkeMedlemIndikator_QNAME, Boolean.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link RegisterOplysningBaseType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:oio:sagdok:person:1.0.0", name = "RegisterOplysningBase")
    public JAXBElement<RegisterOplysningBaseType> createRegisterOplysningBase(RegisterOplysningBaseType value) {
        return new JAXBElement<RegisterOplysningBaseType>(_RegisterOplysningBase_QNAME, RegisterOplysningBaseType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Boolean }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:oio:sagdok:person:1.0.0", name = "TelefonNummerBeskyttelseIndikator")
    public JAXBElement<Boolean> createTelefonNummerBeskyttelseIndikator(Boolean value) {
        return new JAXBElement<Boolean>(_TelefonNummerBeskyttelseIndikator_QNAME, Boolean.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link EgenskabType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:oio:sagdok:person:1.0.0", name = "Egenskab")
    public JAXBElement<EgenskabType> createEgenskab(EgenskabType value) {
        return new JAXBElement<EgenskabType>(_Egenskab_QNAME, EgenskabType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CivilStatusType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:oio:sagdok:person:1.0.0", name = "CivilStatus")
    public JAXBElement<CivilStatusType> createCivilStatus(CivilStatusType value) {
        return new JAXBElement<CivilStatusType>(_CivilStatus_QNAME, CivilStatusType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link PersonFlerRelationType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:oio:sagdok:person:1.0.0", name = "Bopaelssamling")
    public JAXBElement<PersonFlerRelationType> createBopaelssamling(PersonFlerRelationType value) {
        return new JAXBElement<PersonFlerRelationType>(_Bopaelssamling_QNAME, PersonFlerRelationType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link NavnStrukturType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:oio:sagdok:person:1.0.0", name = "NavnStruktur")
    public JAXBElement<NavnStrukturType> createNavnStruktur(NavnStrukturType value) {
        return new JAXBElement<NavnStrukturType>(_NavnStruktur_QNAME, NavnStrukturType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:oio:sagdok:person:1.0.0", name = "KontaktKanalTekst")
    public JAXBElement<String> createKontaktKanalTekst(String value) {
        return new JAXBElement<String>(_KontaktKanalTekst_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link LivStatusType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:oio:sagdok:person:1.0.0", name = "LivStatus")
    public JAXBElement<LivStatusType> createLivStatus(LivStatusType value) {
        return new JAXBElement<LivStatusType>(_LivStatus_QNAME, LivStatusType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link PersonRelationType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:oio:sagdok:person:1.0.0", name = "Moder")
    public JAXBElement<PersonRelationType> createModer(PersonRelationType value) {
        return new JAXBElement<PersonRelationType>(_Moder_QNAME, PersonRelationType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link PersonFlerRelationType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:oio:sagdok:person:1.0.0", name = "ErstatningFor")
    public JAXBElement<PersonFlerRelationType> createErstatningFor(PersonFlerRelationType value) {
        return new JAXBElement<PersonFlerRelationType>(_ErstatningFor_QNAME, PersonFlerRelationType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link PersonFlerRelationType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:oio:sagdok:person:1.0.0", name = "Foraeldremyndighedsboern")
    public JAXBElement<PersonFlerRelationType> createForaeldremyndighedsboern(PersonFlerRelationType value) {
        return new JAXBElement<PersonFlerRelationType>(_Foraeldremyndighedsboern_QNAME, PersonFlerRelationType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link PersonRelationType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:oio:sagdok:person:1.0.0", name = "Aegtefaelle")
    public JAXBElement<PersonRelationType> createAegtefaelle(PersonRelationType value) {
        return new JAXBElement<PersonRelationType>(_Aegtefaelle_QNAME, PersonRelationType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:oio:sagdok:person:1.0.0", name = "PersonIdentifikator")
    public JAXBElement<String> createPersonIdentifikator(String value) {
        return new JAXBElement<String>(_PersonIdentifikator_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:oio:sagdok:person:1.0.0", name = "BegraensetAnvendelseTekst")
    public JAXBElement<String> createBegraensetAnvendelseTekst(String value) {
        return new JAXBElement<String>(_BegraensetAnvendelseTekst_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link UdenlandskBorgerType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:oio:sagdok:person:1.0.0", name = "UdenlandskBorger")
    public JAXBElement<UdenlandskBorgerType> createUdenlandskBorger(UdenlandskBorgerType value) {
        return new JAXBElement<UdenlandskBorgerType>(_UdenlandskBorger_QNAME, UdenlandskBorgerType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link AdresseType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:oio:sagdok:person:1.0.0", name = "AndreAdresser")
    public JAXBElement<AdresseType> createAndreAdresser(AdresseType value) {
        return new JAXBElement<AdresseType>(_AndreAdresser_QNAME, AdresseType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:oio:sagdok:person:1.0.0", name = "PostDistriktTekst")
    public JAXBElement<String> createPostDistriktTekst(String value) {
        return new JAXBElement<String>(_PostDistriktTekst_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link DanskAdresseType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:oio:sagdok:person:1.0.0", name = "DanskAdresse")
    public JAXBElement<DanskAdresseType> createDanskAdresse(DanskAdresseType value) {
        return new JAXBElement<DanskAdresseType>(_DanskAdresse_QNAME, DanskAdresseType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:oio:sagdok:person:1.0.0", name = "ValgkredsDistriktTekst")
    public JAXBElement<String> createValgkredsDistriktTekst(String value) {
        return new JAXBElement<String>(_ValgkredsDistriktTekst_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:oio:sagdok:person:1.0.0", name = "SocialDistriktTekst")
    public JAXBElement<String> createSocialDistriktTekst(String value) {
        return new JAXBElement<String>(_SocialDistriktTekst_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link PersonFlerRelationType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:oio:sagdok:person:1.0.0", name = "RetligHandleevneVaergemaalsindehaver")
    public JAXBElement<PersonFlerRelationType> createRetligHandleevneVaergemaalsindehaver(PersonFlerRelationType value) {
        return new JAXBElement<PersonFlerRelationType>(_RetligHandleevneVaergemaalsindehaver_QNAME, PersonFlerRelationType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link RegisterOplysningType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:oio:sagdok:person:1.0.0", name = "RegisterOplysning")
    public JAXBElement<RegisterOplysningType> createRegisterOplysning(RegisterOplysningType value) {
        return new JAXBElement<RegisterOplysningType>(_RegisterOplysning_QNAME, RegisterOplysningType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link UkendtBorgerType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:oio:sagdok:person:1.0.0", name = "UkendtBorger")
    public JAXBElement<UkendtBorgerType> createUkendtBorger(UkendtBorgerType value) {
        return new JAXBElement<UkendtBorgerType>(_UkendtBorger_QNAME, UkendtBorgerType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CountryIdentificationCodeType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:oio:sagdok:person:1.0.0", name = "FoedselslandKode")
    public JAXBElement<CountryIdentificationCodeType> createFoedselslandKode(CountryIdentificationCodeType value) {
        return new JAXBElement<CountryIdentificationCodeType>(_FoedselslandKode_QNAME, CountryIdentificationCodeType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:oio:sagdok:person:1.0.0", name = "PolitiDistriktTekst")
    public JAXBElement<String> createPolitiDistriktTekst(String value) {
        return new JAXBElement<String>(_PolitiDistriktTekst_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link GroenlandAdresseType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:oio:sagdok:person:1.0.0", name = "GroenlandAdresse")
    public JAXBElement<GroenlandAdresseType> createGroenlandAdresse(GroenlandAdresseType value) {
        return new JAXBElement<GroenlandAdresseType>(_GroenlandAdresse_QNAME, GroenlandAdresseType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Boolean }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:oio:sagdok:person:1.0.0", name = "NavneAdresseBeskyttelseIndikator")
    public JAXBElement<Boolean> createNavneAdresseBeskyttelseIndikator(Boolean value) {
        return new JAXBElement<Boolean>(_NavneAdresseBeskyttelseIndikator_QNAME, Boolean.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CountryIdentificationCodeType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:oio:sagdok:person:1.0.0", name = "SprogKode")
    public JAXBElement<CountryIdentificationCodeType> createSprogKode(CountryIdentificationCodeType value) {
        return new JAXBElement<CountryIdentificationCodeType>(_SprogKode_QNAME, CountryIdentificationCodeType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link KontaktKanalType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:oio:sagdok:person:1.0.0", name = "NaermestePaaroerende")
    public JAXBElement<KontaktKanalType> createNaermestePaaroerende(KontaktKanalType value) {
        return new JAXBElement<KontaktKanalType>(_NaermestePaaroerende_QNAME, KontaktKanalType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link AndenKontaktKanalType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:oio:sagdok:person:1.0.0", name = "AndenKontaktKanal")
    public JAXBElement<AndenKontaktKanalType> createAndenKontaktKanal(AndenKontaktKanalType value) {
        return new JAXBElement<AndenKontaktKanalType>(_AndenKontaktKanal_QNAME, AndenKontaktKanalType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Boolean }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:oio:sagdok:person:1.0.0", name = "KanBrugesTilSmsIndikator")
    public JAXBElement<Boolean> createKanBrugesTilSmsIndikator(Boolean value) {
        return new JAXBElement<Boolean>(_KanBrugesTilSmsIndikator_QNAME, Boolean.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link KontaktKanalBaseType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:oio:sagdok:person:1.0.0", name = "KontaktKanalBase")
    public JAXBElement<KontaktKanalBaseType> createKontaktKanalBase(KontaktKanalBaseType value) {
        return new JAXBElement<KontaktKanalBaseType>(_KontaktKanalBase_QNAME, KontaktKanalBaseType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link RegistreringType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:oio:sagdok:person:1.0.0", name = "Registrering")
    public JAXBElement<RegistreringType> createRegistrering(RegistreringType value) {
        return new JAXBElement<RegistreringType>(_Registrering_QNAME, RegistreringType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CprBorgerType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:oio:sagdok:person:1.0.0", name = "CprBorger")
    public JAXBElement<CprBorgerType> createCprBorger(CprBorgerType value) {
        return new JAXBElement<CprBorgerType>(_CprBorger_QNAME, CprBorgerType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CivilStatusKodeType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:oio:sagdok:person:1.0.0", name = "CivilStatusKode")
    public JAXBElement<CivilStatusKodeType> createCivilStatusKode(CivilStatusKodeType value) {
        return new JAXBElement<CivilStatusKodeType>(_CivilStatusKode_QNAME, CivilStatusKodeType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link PersonType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:oio:sagdok:person:1.0.0", name = "Person")
    public JAXBElement<PersonType> createPerson(PersonType value) {
        return new JAXBElement<PersonType>(_Person_QNAME, PersonType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link AdresseBaseType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:oio:sagdok:person:1.0.0", name = "AdresseBase")
    public JAXBElement<AdresseBaseType> createAdresseBase(AdresseBaseType value) {
        return new JAXBElement<AdresseBaseType>(_AdresseBase_QNAME, AdresseBaseType.class, null, value);
    }

}
