//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.06.14 at 09:30:07 AM CEST
//


package oio.sagdok.person._1_0;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for RegisterOplysningBaseType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="RegisterOplysningBaseType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;choice>
 *         &lt;element ref="{urn:oio:sagdok:person:1.0.0}UdenlandskBorger"/>
 *         &lt;element ref="{urn:oio:sagdok:person:1.0.0}CprBorger"/>
 *         &lt;element ref="{urn:oio:sagdok:person:1.0.0}UkendtBorger"/>
 *       &lt;/choice>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "RegisterOplysningBaseType", propOrder = {
    "udenlandskBorger",
    "cprBorger",
    "ukendtBorger"
})
@XmlSeeAlso({
    RegisterOplysningType.class
})
public class RegisterOplysningBaseType {

    @XmlElement(name = "UdenlandskBorger")
    protected UdenlandskBorgerType udenlandskBorger;
    @XmlElement(name = "CprBorger")
    protected CprBorgerType cprBorger;
    @XmlElement(name = "UkendtBorger")
    protected UkendtBorgerType ukendtBorger;

    /**
     * Gets the value of the udenlandskBorger property.
     * 
     * @return
     *     possible object is
     *     {@link UdenlandskBorgerType }
     *     
     */
    public UdenlandskBorgerType getUdenlandskBorger() {
        return udenlandskBorger;
    }

    /**
     * Sets the value of the udenlandskBorger property.
     * 
     * @param value
     *     allowed object is
     *     {@link UdenlandskBorgerType }
     *     
     */
    public void setUdenlandskBorger(UdenlandskBorgerType value) {
        this.udenlandskBorger = value;
    }

    /**
     * Gets the value of the cprBorger property.
     * 
     * @return
     *     possible object is
     *     {@link CprBorgerType }
     *     
     */
    public CprBorgerType getCprBorger() {
        return cprBorger;
    }

    /**
     * Sets the value of the cprBorger property.
     * 
     * @param value
     *     allowed object is
     *     {@link CprBorgerType }
     *     
     */
    public void setCprBorger(CprBorgerType value) {
        this.cprBorger = value;
    }

    /**
     * Gets the value of the ukendtBorger property.
     * 
     * @return
     *     possible object is
     *     {@link UkendtBorgerType }
     *     
     */
    public UkendtBorgerType getUkendtBorger() {
        return ukendtBorger;
    }

    /**
     * Sets the value of the ukendtBorger property.
     * 
     * @param value
     *     allowed object is
     *     {@link UkendtBorgerType }
     *     
     */
    public void setUkendtBorger(UkendtBorgerType value) {
        this.ukendtBorger = value;
    }

}
