//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.06.14 at 09:30:07 AM CEST
//


package dk.oio.rep.bbr_dk.xml.schemas._2006._09._30;

import java.math.BigDecimal;
import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.datatype.XMLGregorianCalendar;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the dk.oio.rep.bbr_dk.xml.schemas._2006._09._30 package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _GeographicPointLocation_QNAME = new QName("http://rep.oio.dk/bbr.dk/xml/schemas/2006/09/30/", "GeographicPointLocation");
    private final static QName _AddressPointStatusStructure_QNAME = new QName("http://rep.oio.dk/bbr.dk/xml/schemas/2006/09/30/", "AddressPointStatusStructure");
    private final static QName _AddressPointIdentifier_QNAME = new QName("http://rep.oio.dk/bbr.dk/xml/schemas/2006/09/30/", "AddressPointIdentifier");
    private final static QName _AddressPointRevisionDateTime_QNAME = new QName("http://rep.oio.dk/bbr.dk/xml/schemas/2006/09/30/", "AddressPointRevisionDateTime");
    private final static QName _GeographicCoordinateTuple_QNAME = new QName("http://rep.oio.dk/bbr.dk/xml/schemas/2006/09/30/", "GeographicCoordinateTuple");
    private final static QName _GeographicNorthingMeasure_QNAME = new QName("http://rep.oio.dk/bbr.dk/xml/schemas/2006/09/30/", "GeographicNorthingMeasure");
    private final static QName _AddressCoordinateQualityClassCode_QNAME = new QName("http://rep.oio.dk/bbr.dk/xml/schemas/2006/09/30/", "AddressCoordinateQualityClassCode");
    private final static QName _AddressPointValidEndDateTime_QNAME = new QName("http://rep.oio.dk/bbr.dk/xml/schemas/2006/09/30/", "AddressPointValidEndDateTime");
    private final static QName _GeographicHeightMeasure_QNAME = new QName("http://rep.oio.dk/bbr.dk/xml/schemas/2006/09/30/", "GeographicHeightMeasure");
    private final static QName _GeographicEastingMeasure_QNAME = new QName("http://rep.oio.dk/bbr.dk/xml/schemas/2006/09/30/", "GeographicEastingMeasure");
    private final static QName _AddressPoint_QNAME = new QName("http://rep.oio.dk/bbr.dk/xml/schemas/2006/09/30/", "AddressPoint");
    private final static QName _AddressPointValidStartDateTime_QNAME = new QName("http://rep.oio.dk/bbr.dk/xml/schemas/2006/09/30/", "AddressPointValidStartDateTime");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: dk.oio.rep.bbr_dk.xml.schemas._2006._09._30
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link GeographicCoordinateTupleType }
     * 
     */
    public GeographicCoordinateTupleType createGeographicCoordinateTupleType() {
        return new GeographicCoordinateTupleType();
    }

    /**
     * Create an instance of {@link AddressPointType }
     * 
     */
    public AddressPointType createAddressPointType() {
        return new AddressPointType();
    }

    /**
     * Create an instance of {@link GeographicPointLocationType }
     * 
     */
    public GeographicPointLocationType createGeographicPointLocationType() {
        return new GeographicPointLocationType();
    }

    /**
     * Create an instance of {@link AddressPointStatusStructureType }
     * 
     */
    public AddressPointStatusStructureType createAddressPointStatusStructureType() {
        return new AddressPointStatusStructureType();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link GeographicPointLocationType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://rep.oio.dk/bbr.dk/xml/schemas/2006/09/30/", name = "GeographicPointLocation")
    public JAXBElement<GeographicPointLocationType> createGeographicPointLocation(GeographicPointLocationType value) {
        return new JAXBElement<GeographicPointLocationType>(_GeographicPointLocation_QNAME, GeographicPointLocationType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link AddressPointStatusStructureType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://rep.oio.dk/bbr.dk/xml/schemas/2006/09/30/", name = "AddressPointStatusStructure")
    public JAXBElement<AddressPointStatusStructureType> createAddressPointStatusStructure(AddressPointStatusStructureType value) {
        return new JAXBElement<AddressPointStatusStructureType>(_AddressPointStatusStructure_QNAME, AddressPointStatusStructureType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://rep.oio.dk/bbr.dk/xml/schemas/2006/09/30/", name = "AddressPointIdentifier")
    public JAXBElement<String> createAddressPointIdentifier(String value) {
        return new JAXBElement<String>(_AddressPointIdentifier_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link XMLGregorianCalendar }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://rep.oio.dk/bbr.dk/xml/schemas/2006/09/30/", name = "AddressPointRevisionDateTime")
    public JAXBElement<XMLGregorianCalendar> createAddressPointRevisionDateTime(XMLGregorianCalendar value) {
        return new JAXBElement<XMLGregorianCalendar>(_AddressPointRevisionDateTime_QNAME, XMLGregorianCalendar.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link GeographicCoordinateTupleType }{@code >}}
     *
     */
    @XmlElementDecl(namespace = "http://rep.oio.dk/bbr.dk/xml/schemas/2006/09/30/", name = "GeographicCoordinateTuple")
    public JAXBElement<GeographicCoordinateTupleType> createGeographicCoordinateTuple(GeographicCoordinateTupleType value) {
        return new JAXBElement<GeographicCoordinateTupleType>(_GeographicCoordinateTuple_QNAME, GeographicCoordinateTupleType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigDecimal }{@code >}}
     *
     */
    @XmlElementDecl(namespace = "http://rep.oio.dk/bbr.dk/xml/schemas/2006/09/30/", name = "GeographicNorthingMeasure")
    public JAXBElement<BigDecimal> createGeographicNorthingMeasure(BigDecimal value) {
        return new JAXBElement<BigDecimal>(_GeographicNorthingMeasure_QNAME, BigDecimal.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link AddressCoordinateQualityClassCodeType }{@code >}}
     *
     */
    @XmlElementDecl(namespace = "http://rep.oio.dk/bbr.dk/xml/schemas/2006/09/30/", name = "AddressCoordinateQualityClassCode")
    public JAXBElement<AddressCoordinateQualityClassCodeType> createAddressCoordinateQualityClassCode(AddressCoordinateQualityClassCodeType value) {
        return new JAXBElement<AddressCoordinateQualityClassCodeType>(_AddressCoordinateQualityClassCode_QNAME, AddressCoordinateQualityClassCodeType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link XMLGregorianCalendar }{@code >}}
     *
     */
    @XmlElementDecl(namespace = "http://rep.oio.dk/bbr.dk/xml/schemas/2006/09/30/", name = "AddressPointValidEndDateTime")
    public JAXBElement<XMLGregorianCalendar> createAddressPointValidEndDateTime(XMLGregorianCalendar value) {
        return new JAXBElement<XMLGregorianCalendar>(_AddressPointValidEndDateTime_QNAME, XMLGregorianCalendar.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigDecimal }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://rep.oio.dk/bbr.dk/xml/schemas/2006/09/30/", name = "GeographicHeightMeasure")
    public JAXBElement<BigDecimal> createGeographicHeightMeasure(BigDecimal value) {
        return new JAXBElement<BigDecimal>(_GeographicHeightMeasure_QNAME, BigDecimal.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigDecimal }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://rep.oio.dk/bbr.dk/xml/schemas/2006/09/30/", name = "GeographicEastingMeasure")
    public JAXBElement<BigDecimal> createGeographicEastingMeasure(BigDecimal value) {
        return new JAXBElement<BigDecimal>(_GeographicEastingMeasure_QNAME, BigDecimal.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link AddressPointType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://rep.oio.dk/bbr.dk/xml/schemas/2006/09/30/", name = "AddressPoint")
    public JAXBElement<AddressPointType> createAddressPoint(AddressPointType value) {
        return new JAXBElement<AddressPointType>(_AddressPoint_QNAME, AddressPointType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link XMLGregorianCalendar }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://rep.oio.dk/bbr.dk/xml/schemas/2006/09/30/", name = "AddressPointValidStartDateTime")
    public JAXBElement<XMLGregorianCalendar> createAddressPointValidStartDateTime(XMLGregorianCalendar value) {
        return new JAXBElement<XMLGregorianCalendar>(_AddressPointValidStartDateTime_QNAME, XMLGregorianCalendar.class, null, value);
    }

}
