//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2011.06.14 at 09:30:07 AM CEST
//


package oio.sagdok._3_0;

import java.math.BigInteger;
import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.datatype.XMLGregorianCalendar;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each
 * Java content interface and Java element interface
 * generated in the oio.sagdok._3_0 package.
 * <p>An ObjectFactory allows you to programatically
 * construct new instances of the Java representation
 * for XML content. The Java representation of XML
 * content can consist of schema derived interfaces
 * and classes representing the binding of schema
 * type definitions, element declarations and model
 * groups.  Factory methods for each of these are
 * provided in this class.
 *
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _MyndighedRelation_QNAME = new QName("urn:oio:sagdok:3.0.0", "MyndighedRelation");
    private final static QName _SoegMyndighed_QNAME = new QName("urn:oio:sagdok:3.0.0", "SoegMyndighed");
    private final static QName _Opgaver_QNAME = new QName("urn:oio:sagdok:3.0.0", "Opgaver");
    private final static QName _BrugerTypeTekst_QNAME = new QName("urn:oio:sagdok:3.0.0", "BrugerTypeTekst");
    private final static QName _SoegTilknyttedeItSystemer_QNAME = new QName("urn:oio:sagdok:3.0.0", "SoegTilknyttedeItSystemer");
    private final static QName _SoegFunktionstype_QNAME = new QName("urn:oio:sagdok:3.0.0", "SoegFunktionstype");
    private final static QName _VirkningTilFilter_QNAME = new QName("urn:oio:sagdok:3.0.0", "VirkningTilFilter");
    private final static QName _BrugerTyper_QNAME = new QName("urn:oio:sagdok:3.0.0", "BrugerTyper");
    private final static QName _InteressefaellesskabFlerRelation_QNAME = new QName("urn:oio:sagdok:3.0.0", "InteressefaellesskabFlerRelation");
    private final static QName _PersonFlerRelation_QNAME = new QName("urn:oio:sagdok:3.0.0", "PersonFlerRelation");
    private final static QName _LokalUdvidelse_QNAME = new QName("urn:oio:sagdok:3.0.0", "LokalUdvidelse");
    private final static QName _SoegTilknyttedeEnheder_QNAME = new QName("urn:oio:sagdok:3.0.0", "SoegTilknyttedeEnheder");
    private final static QName _URNIdentifikator_QNAME = new QName("urn:oio:sagdok:3.0.0", "URNIdentifikator");
    private final static QName _TilknyttedeItSystemer_QNAME = new QName("urn:oio:sagdok:3.0.0", "TilknyttedeItSystemer");
    private final static QName _OrganisationEnhedFlerRelation_QNAME = new QName("urn:oio:sagdok:3.0.0", "OrganisationEnhedFlerRelation");
    private final static QName _SoegRelation_QNAME = new QName("urn:oio:sagdok:3.0.0", "SoegRelation");
    private final static QName _ImportInput_QNAME = new QName("urn:oio:sagdok:3.0.0", "ImportInput");
    private final static QName _BrugerFlerRelation_QNAME = new QName("urn:oio:sagdok:3.0.0", "BrugerFlerRelation");
    private final static QName _TilknyttedeEnheder_QNAME = new QName("urn:oio:sagdok:3.0.0", "TilknyttedeEnheder");
    private final static QName _MaksimalAntalKvantitet_QNAME = new QName("urn:oio:sagdok:3.0.0", "MaksimalAntalKvantitet");
    private final static QName _GraenseIndikator_QNAME = new QName("urn:oio:sagdok:3.0.0", "GraenseIndikator");
    private final static QName _InteressefaellesskabNavn_QNAME = new QName("urn:oio:sagdok:3.0.0", "InteressefaellesskabNavn");
    private final static QName _FoersteResultatReference_QNAME = new QName("urn:oio:sagdok:3.0.0", "FoersteResultatReference");
    private final static QName _OrganisationFunktionFlerRelation_QNAME = new QName("urn:oio:sagdok:3.0.0", "OrganisationFunktionFlerRelation");
    private final static QName _TilknyttedeBrugere_QNAME = new QName("urn:oio:sagdok:3.0.0", "TilknyttedeBrugere");
    private final static QName _RetInput_QNAME = new QName("urn:oio:sagdok:3.0.0", "RetInput");
    private final static QName _Myndighedstype_QNAME = new QName("urn:oio:sagdok:3.0.0", "Myndighedstype");
    private final static QName _StandardRetur_QNAME = new QName("urn:oio:sagdok:3.0.0", "StandardRetur");
    private final static QName _SoegOutput_QNAME = new QName("urn:oio:sagdok:3.0.0", "SoegOutput");
    private final static QName _IdListe_QNAME = new QName("urn:oio:sagdok:3.0.0", "IdListe");
    private final static QName _UnikId_QNAME = new QName("urn:oio:sagdok:3.0.0", "UnikId");
    private final static QName _SoegEnhedstype_QNAME = new QName("urn:oio:sagdok:3.0.0", "SoegEnhedstype");
    private final static QName _AdresseFlerRelation_QNAME = new QName("urn:oio:sagdok:3.0.0", "AdresseFlerRelation");
    private final static QName _SoegSystemTyper_QNAME = new QName("urn:oio:sagdok:3.0.0", "SoegSystemTyper");
    private final static QName _SagDokObjekt_QNAME = new QName("urn:oio:sagdok:3.0.0", "SagDokObjekt");
    private final static QName _KlasseFlerRelation_QNAME = new QName("urn:oio:sagdok:3.0.0", "KlasseFlerRelation");
    private final static QName _OrganisationRelation_QNAME = new QName("urn:oio:sagdok:3.0.0", "OrganisationRelation");
    private final static QName _TilknyttedeInteressefaellesskaber_QNAME = new QName("urn:oio:sagdok:3.0.0", "TilknyttedeInteressefaellesskaber");
    private final static QName _SoegSkatteenhed_QNAME = new QName("urn:oio:sagdok:3.0.0", "SoegSkatteenhed");
    private final static QName _Tilhoerer_QNAME = new QName("urn:oio:sagdok:3.0.0", "Tilhoerer");
    private final static QName _Virksomhedstype_QNAME = new QName("urn:oio:sagdok:3.0.0", "Virksomhedstype");
    private final static QName _InteressefaellesskabTypeTekst_QNAME = new QName("urn:oio:sagdok:3.0.0", "InteressefaellesskabTypeTekst");
    private final static QName _VirkningFraFilter_QNAME = new QName("urn:oio:sagdok:3.0.0", "VirkningFraFilter");
    private final static QName _LivscyklusKode_QNAME = new QName("urn:oio:sagdok:3.0.0", "LivscyklusKode");
    private final static QName _SoegTilknyttedeFunktioner_QNAME = new QName("urn:oio:sagdok:3.0.0", "SoegTilknyttedeFunktioner");
    private final static QName _OrganisationFlerRelation_QNAME = new QName("urn:oio:sagdok:3.0.0", "OrganisationFlerRelation");
    private final static QName _ItSystemFlerRelation_QNAME = new QName("urn:oio:sagdok:3.0.0", "ItSystemFlerRelation");
    private final static QName _LaesInput_QNAME = new QName("urn:oio:sagdok:3.0.0", "LaesInput");
    private final static QName _Relation_QNAME = new QName("urn:oio:sagdok:3.0.0", "Relation");
    private final static QName _SoegBrugerTyper_QNAME = new QName("urn:oio:sagdok:3.0.0", "SoegBrugerTyper");
    private final static QName _SoegTilknyttedePersoner_QNAME = new QName("urn:oio:sagdok:3.0.0", "SoegTilknyttedePersoner");
    private final static QName _FraTidspunkt_QNAME = new QName("urn:oio:sagdok:3.0.0", "FraTidspunkt");
    private final static QName _KlasseRelation_QNAME = new QName("urn:oio:sagdok:3.0.0", "KlasseRelation");
    private final static QName _BrugervendtNoegleTekst_QNAME = new QName("urn:oio:sagdok:3.0.0", "BrugervendtNoegleTekst");
    private final static QName _ListInput_QNAME = new QName("urn:oio:sagdok:3.0.0", "ListInput");
    private final static QName _SoegTilknyttedeInteressefaellesskaber_QNAME = new QName("urn:oio:sagdok:3.0.0", "SoegTilknyttedeInteressefaellesskaber");
    private final static QName _RegistreringFraFilter_QNAME = new QName("urn:oio:sagdok:3.0.0", "RegistreringFraFilter");
    private final static QName _Funktionstype_QNAME = new QName("urn:oio:sagdok:3.0.0", "Funktionstype");
    private final static QName _OpretInput_QNAME = new QName("urn:oio:sagdok:3.0.0", "OpretInput");
    private final static QName _EnhedNavn_QNAME = new QName("urn:oio:sagdok:3.0.0", "EnhedNavn");
    private final static QName _BrugerRef_QNAME = new QName("urn:oio:sagdok:3.0.0", "BrugerRef");
    private final static QName _Tidspunkt_QNAME = new QName("urn:oio:sagdok:3.0.0", "Tidspunkt");
    private final static QName _RegistreringTilFilter_QNAME = new QName("urn:oio:sagdok:3.0.0", "RegistreringTilFilter");
    private final static QName _SoegBranche_QNAME = new QName("urn:oio:sagdok:3.0.0", "SoegBranche");
    private final static QName _ItSystemNavn_QNAME = new QName("urn:oio:sagdok:3.0.0", "ItSystemNavn");
    private final static QName _BasicOutput_QNAME = new QName("urn:oio:sagdok:3.0.0", "BasicOutput");
    private final static QName _SoegSagDokObjekt_QNAME = new QName("urn:oio:sagdok:3.0.0", "SoegSagDokObjekt");
    private final static QName _Virkning_QNAME = new QName("urn:oio:sagdok:3.0.0", "Virkning");
    private final static QName _SoegOverordnet_QNAME = new QName("urn:oio:sagdok:3.0.0", "SoegOverordnet");
    private final static QName _StatusKode_QNAME = new QName("urn:oio:sagdok:3.0.0", "StatusKode");
    private final static QName _Virksomhed_QNAME = new QName("urn:oio:sagdok:3.0.0", "Virksomhed");
    private final static QName _UUIDIdentifikator_QNAME = new QName("urn:oio:sagdok:3.0.0", "UUIDIdentifikator");
    private final static QName _FlerRelation_QNAME = new QName("urn:oio:sagdok:3.0.0", "FlerRelation");
    private final static QName _ItSystemTypeTekst_QNAME = new QName("urn:oio:sagdok:3.0.0", "ItSystemTypeTekst");
    private final static QName _ListOutput_QNAME = new QName("urn:oio:sagdok:3.0.0", "ListOutput");
    private final static QName _FunktionNavn_QNAME = new QName("urn:oio:sagdok:3.0.0", "FunktionNavn");
    private final static QName _Registrering_QNAME = new QName("urn:oio:sagdok:3.0.0", "Registrering");
    private final static QName _Overordnet_QNAME = new QName("urn:oio:sagdok:3.0.0", "Overordnet");
    private final static QName _TilknyttedePersoner_QNAME = new QName("urn:oio:sagdok:3.0.0", "TilknyttedePersoner");
    private final static QName _SoegTilknyttedeBrugere_QNAME = new QName("urn:oio:sagdok:3.0.0", "SoegTilknyttedeBrugere");
    private final static QName _OrganisationNavn_QNAME = new QName("urn:oio:sagdok:3.0.0", "OrganisationNavn");
    private final static QName _AktoerRef_QNAME = new QName("urn:oio:sagdok:3.0.0", "AktoerRef");
    private final static QName _KaldenavnTekst_QNAME = new QName("urn:oio:sagdok:3.0.0", "KaldenavnTekst");
    private final static QName _Ansatte_QNAME = new QName("urn:oio:sagdok:3.0.0", "Ansatte");
    private final static QName _SoegVirksomhedstype_QNAME = new QName("urn:oio:sagdok:3.0.0", "SoegVirksomhedstype");
    private final static QName _SoegTilknyttedeOrganisationer_QNAME = new QName("urn:oio:sagdok:3.0.0", "SoegTilknyttedeOrganisationer");
    private final static QName _SoegMyndighedstype_QNAME = new QName("urn:oio:sagdok:3.0.0", "SoegMyndighedstype");
    private final static QName _TidsstempelDatoTid_QNAME = new QName("urn:oio:sagdok:3.0.0", "TidsstempelDatoTid");
    private final static QName _AktoerTypeKode_QNAME = new QName("urn:oio:sagdok:3.0.0", "AktoerTypeKode");
    private final static QName _SoegInput_QNAME = new QName("urn:oio:sagdok:3.0.0", "SoegInput");
    private final static QName _Adresser_QNAME = new QName("urn:oio:sagdok:3.0.0", "Adresser");
    private final static QName _SoegRegistrering_QNAME = new QName("urn:oio:sagdok:3.0.0", "SoegRegistrering");
    private final static QName _TilTidspunkt_QNAME = new QName("urn:oio:sagdok:3.0.0", "TilTidspunkt");
    private final static QName _SoegOpgaver_QNAME = new QName("urn:oio:sagdok:3.0.0", "SoegOpgaver");
    private final static QName _LaesFiltreretOutput_QNAME = new QName("urn:oio:sagdok:3.0.0", "LaesFiltreretOutput");
    private final static QName _SoegAnsatte_QNAME = new QName("urn:oio:sagdok:3.0.0", "SoegAnsatte");
    private final static QName _TilknyttedeOrganisationer_QNAME = new QName("urn:oio:sagdok:3.0.0", "TilknyttedeOrganisationer");
    private final static QName _OrganisationEnhedRelation_QNAME = new QName("urn:oio:sagdok:3.0.0", "OrganisationEnhedRelation");
    private final static QName _SoegAdresser_QNAME = new QName("urn:oio:sagdok:3.0.0", "SoegAdresser");
    private final static QName _Skatteenhed_QNAME = new QName("urn:oio:sagdok:3.0.0", "Skatteenhed");
    private final static QName _UuidNoteInput_QNAME = new QName("urn:oio:sagdok:3.0.0", "UuidNoteInput");
    private final static QName _NoteTekst_QNAME = new QName("urn:oio:sagdok:3.0.0", "NoteTekst");
    private final static QName _SoegVirksomhed_QNAME = new QName("urn:oio:sagdok:3.0.0", "SoegVirksomhed");
    private final static QName _SoegProduktionsenhed_QNAME = new QName("urn:oio:sagdok:3.0.0", "SoegProduktionsenhed");
    private final static QName _KonfigurationReference_QNAME = new QName("urn:oio:sagdok:3.0.0", "KonfigurationReference");
    private final static QName _FejlbeskedTekst_QNAME = new QName("urn:oio:sagdok:3.0.0", "FejlbeskedTekst");
    private final static QName _Produktionsenhed_QNAME = new QName("urn:oio:sagdok:3.0.0", "Produktionsenhed");
    private final static QName _SoegVirkning_QNAME = new QName("urn:oio:sagdok:3.0.0", "SoegVirkning");
    private final static QName _TilknyttedeFunktioner_QNAME = new QName("urn:oio:sagdok:3.0.0", "TilknyttedeFunktioner");
    private final static QName _SystemTyper_QNAME = new QName("urn:oio:sagdok:3.0.0", "SystemTyper");
    private final static QName _ReferenceID_QNAME = new QName("urn:oio:sagdok:3.0.0", "ReferenceID");
    private final static QName _BrugerNavn_QNAME = new QName("urn:oio:sagdok:3.0.0", "BrugerNavn");
    private final static QName _SoegTilhoerer_QNAME = new QName("urn:oio:sagdok:3.0.0", "SoegTilhoerer");
    private final static QName _Enhedstype_QNAME = new QName("urn:oio:sagdok:3.0.0", "Enhedstype");
    private final static QName _VirksomhedRelation_QNAME = new QName("urn:oio:sagdok:3.0.0", "VirksomhedRelation");
    private final static QName _Myndighed_QNAME = new QName("urn:oio:sagdok:3.0.0", "Myndighed");
    private final static QName _Branche_QNAME = new QName("urn:oio:sagdok:3.0.0", "Branche");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: oio.sagdok._3_0
     *
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link PersonFlerRelationType }
     *
     */
    public PersonFlerRelationType createPersonFlerRelationType() {
        return new PersonFlerRelationType();
    }

    /**
     * Create an instance of {@link MyndighedRelationType }
     *
     */
    public MyndighedRelationType createMyndighedRelationType() {
        return new MyndighedRelationType();
    }

    /**
     * Create an instance of {@link TidspunktType }
     *
     */
    public TidspunktType createTidspunktType() {
        return new TidspunktType();
    }

    /**
     * Create an instance of {@link SoegRelationType }
     *
     */
    public SoegRelationType createSoegRelationType() {
        return new SoegRelationType();
    }

    /**
     * Create an instance of {@link KlasseRelationType }
     *
     */
    public KlasseRelationType createKlasseRelationType() {
        return new KlasseRelationType();
    }

    /**
     * Create an instance of {@link KlasseFlerRelationType }
     *
     */
    public KlasseFlerRelationType createKlasseFlerRelationType() {
        return new KlasseFlerRelationType();
    }

    /**
     * Create an instance of {@link ListInputType }
     *
     */
    public ListInputType createListInputType() {
        return new ListInputType();
    }

    /**
     * Create an instance of {@link InteressefaellesskabFlerRelationType }
     *
     */
    public InteressefaellesskabFlerRelationType createInteressefaellesskabFlerRelationType() {
        return new InteressefaellesskabFlerRelationType();
    }

    /**
     * Create an instance of {@link OpretInputType }
     *
     */
    public OpretInputType createOpretInputType() {
        return new OpretInputType();
    }

    /**
     * Create an instance of {@link UnikIdType }
     *
     */
    public UnikIdType createUnikIdType() {
        return new UnikIdType();
    }

    /**
     * Create an instance of {@link LokalUdvidelseType }
     *
     */
    public LokalUdvidelseType createLokalUdvidelseType() {
        return new LokalUdvidelseType();
    }

    /**
     * Create an instance of {@link ItSystemFlerRelationType }
     *
     */
    public ItSystemFlerRelationType createItSystemFlerRelationType() {
        return new ItSystemFlerRelationType();
    }

    /**
     * Create an instance of {@link BasicOutputType }
     *
     */
    public BasicOutputType createBasicOutputType() {
        return new BasicOutputType();
    }

    /**
     * Create an instance of {@link OrganisationEnhedFlerRelationType }
     *
     */
    public OrganisationEnhedFlerRelationType createOrganisationEnhedFlerRelationType() {
        return new OrganisationEnhedFlerRelationType();
    }

    /**
     * Create an instance of {@link VirkningType }
     *
     */
    public VirkningType createVirkningType() {
        return new VirkningType();
    }

    /**
     * Create an instance of {@link SoegSagDokObjektType }
     *
     */
    public SoegSagDokObjektType createSoegSagDokObjektType() {
        return new SoegSagDokObjektType();
    }

    /**
     * Create an instance of {@link ImportInputType }
     *
     */
    public ImportInputType createImportInputType() {
        return new ImportInputType();
    }

    /**
     * Create an instance of {@link BrugerFlerRelationType }
     *
     */
    public BrugerFlerRelationType createBrugerFlerRelationType() {
        return new BrugerFlerRelationType();
    }

    /**
     * Create an instance of {@link VirksomhedRelationType }
     *
     */
    public VirksomhedRelationType createVirksomhedRelationType() {
        return new VirksomhedRelationType();
    }

    /**
     * Create an instance of {@link FlerRelationType }
     *
     */
    public FlerRelationType createFlerRelationType() {
        return new FlerRelationType();
    }

    /**
     * Create an instance of {@link ListOutputType }
     *
     */
    public ListOutputType createListOutputType() {
        return new ListOutputType();
    }

    /**
     * Create an instance of {@link OrganisationFunktionFlerRelationType }
     *
     */
    public OrganisationFunktionFlerRelationType createOrganisationFunktionFlerRelationType() {
        return new OrganisationFunktionFlerRelationType();
    }

    /**
     * Create an instance of {@link RetInputType }
     *
     */
    public RetInputType createRetInputType() {
        return new RetInputType();
    }

    /**
     * Create an instance of {@link StandardReturType }
     *
     */
    public StandardReturType createStandardReturType() {
        return new StandardReturType();
    }

    /**
     * Create an instance of {@link RegistreringType }
     *
     */
    public RegistreringType createRegistreringType() {
        return new RegistreringType();
    }

    /**
     * Create an instance of {@link OrganisationEnhedRelationType }
     *
     */
    public OrganisationEnhedRelationType createOrganisationEnhedRelationType() {
        return new OrganisationEnhedRelationType();
    }

    /**
     * Create an instance of {@link SoegOutputType }
     *
     */
    public SoegOutputType createSoegOutputType() {
        return new SoegOutputType();
    }

    /**
     * Create an instance of {@link IdListeType }
     *
     */
    public IdListeType createIdListeType() {
        return new IdListeType();
    }

    /**
     * Create an instance of {@link SoegInputType }
     *
     */
    public SoegInputType createSoegInputType() {
        return new SoegInputType();
    }

    /**
     * Create an instance of {@link AdresseFlerRelationType }
     *
     */
    public AdresseFlerRelationType createAdresseFlerRelationType() {
        return new AdresseFlerRelationType();
    }

    /**
     * Create an instance of {@link LaesFiltreretOutputType }
     *
     */
    public LaesFiltreretOutputType createLaesFiltreretOutputType() {
        return new LaesFiltreretOutputType();
    }

    /**
     * Create an instance of {@link SoegRegistreringType }
     *
     */
    public SoegRegistreringType createSoegRegistreringType() {
        return new SoegRegistreringType();
    }

    /**
     * Create an instance of {@link OrganisationFlerRelationType }
     *
     */
    public OrganisationFlerRelationType createOrganisationFlerRelationType() {
        return new OrganisationFlerRelationType();
    }

    /**
     * Create an instance of {@link SagDokObjektType }
     *
     */
    public SagDokObjektType createSagDokObjektType() {
        return new SagDokObjektType();
    }

    /**
     * Create an instance of {@link OrganisationRelationType }
     *
     */
    public OrganisationRelationType createOrganisationRelationType() {
        return new OrganisationRelationType();
    }

    /**
     * Create an instance of {@link UuidNoteInputType }
     *
     */
    public UuidNoteInputType createUuidNoteInputType() {
        return new UuidNoteInputType();
    }

    /**
     * Create an instance of {@link SoegVirkningType }
     *
     */
    public SoegVirkningType createSoegVirkningType() {
        return new SoegVirkningType();
    }

    /**
     * Create an instance of {@link LaesInputType }
     *
     */
    public LaesInputType createLaesInputType() {
        return new LaesInputType();
    }

    /**
     * Create an instance of {@link RelationType }
     *
     */
    public RelationType createRelationType() {
        return new RelationType();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link MyndighedRelationType }{@code >}}
     *
     */
    @XmlElementDecl(namespace = "urn:oio:sagdok:3.0.0", name = "MyndighedRelation")
    public JAXBElement<MyndighedRelationType> createMyndighedRelation(MyndighedRelationType value) {
        return new JAXBElement<MyndighedRelationType>(_MyndighedRelation_QNAME, MyndighedRelationType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link SoegRelationType }{@code >}}
     *
     */
    @XmlElementDecl(namespace = "urn:oio:sagdok:3.0.0", name = "SoegMyndighed")
    public JAXBElement<SoegRelationType> createSoegMyndighed(SoegRelationType value) {
        return new JAXBElement<SoegRelationType>(_SoegMyndighed_QNAME, SoegRelationType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link KlasseFlerRelationType }{@code >}}
     *
     */
    @XmlElementDecl(namespace = "urn:oio:sagdok:3.0.0", name = "Opgaver")
    public JAXBElement<KlasseFlerRelationType> createOpgaver(KlasseFlerRelationType value) {
        return new JAXBElement<KlasseFlerRelationType>(_Opgaver_QNAME, KlasseFlerRelationType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     *
     */
    @XmlElementDecl(namespace = "urn:oio:sagdok:3.0.0", name = "BrugerTypeTekst")
    public JAXBElement<String> createBrugerTypeTekst(String value) {
        return new JAXBElement<String>(_BrugerTypeTekst_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link SoegRelationType }{@code >}}
     *
     */
    @XmlElementDecl(namespace = "urn:oio:sagdok:3.0.0", name = "SoegTilknyttedeItSystemer")
    public JAXBElement<SoegRelationType> createSoegTilknyttedeItSystemer(SoegRelationType value) {
        return new JAXBElement<SoegRelationType>(_SoegTilknyttedeItSystemer_QNAME, SoegRelationType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link SoegRelationType }{@code >}}
     *
     */
    @XmlElementDecl(namespace = "urn:oio:sagdok:3.0.0", name = "SoegFunktionstype")
    public JAXBElement<SoegRelationType> createSoegFunktionstype(SoegRelationType value) {
        return new JAXBElement<SoegRelationType>(_SoegFunktionstype_QNAME, SoegRelationType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TidspunktType }{@code >}}
     *
     */
    @XmlElementDecl(namespace = "urn:oio:sagdok:3.0.0", name = "VirkningTilFilter")
    public JAXBElement<TidspunktType> createVirkningTilFilter(TidspunktType value) {
        return new JAXBElement<TidspunktType>(_VirkningTilFilter_QNAME, TidspunktType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link KlasseFlerRelationType }{@code >}}
     *
     */
    @XmlElementDecl(namespace = "urn:oio:sagdok:3.0.0", name = "BrugerTyper")
    public JAXBElement<KlasseFlerRelationType> createBrugerTyper(KlasseFlerRelationType value) {
        return new JAXBElement<KlasseFlerRelationType>(_BrugerTyper_QNAME, KlasseFlerRelationType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link InteressefaellesskabFlerRelationType }{@code >}}
     *
     */
    @XmlElementDecl(namespace = "urn:oio:sagdok:3.0.0", name = "InteressefaellesskabFlerRelation")
    public JAXBElement<InteressefaellesskabFlerRelationType> createInteressefaellesskabFlerRelation(InteressefaellesskabFlerRelationType value) {
        return new JAXBElement<InteressefaellesskabFlerRelationType>(_InteressefaellesskabFlerRelation_QNAME, InteressefaellesskabFlerRelationType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link PersonFlerRelationType }{@code >}}
     *
     */
    @XmlElementDecl(namespace = "urn:oio:sagdok:3.0.0", name = "PersonFlerRelation")
    public JAXBElement<PersonFlerRelationType> createPersonFlerRelation(PersonFlerRelationType value) {
        return new JAXBElement<PersonFlerRelationType>(_PersonFlerRelation_QNAME, PersonFlerRelationType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link LokalUdvidelseType }{@code >}}
     *
     */
    @XmlElementDecl(namespace = "urn:oio:sagdok:3.0.0", name = "LokalUdvidelse")
    public JAXBElement<LokalUdvidelseType> createLokalUdvidelse(LokalUdvidelseType value) {
        return new JAXBElement<LokalUdvidelseType>(_LokalUdvidelse_QNAME, LokalUdvidelseType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link SoegRelationType }{@code >}}
     *
     */
    @XmlElementDecl(namespace = "urn:oio:sagdok:3.0.0", name = "SoegTilknyttedeEnheder")
    public JAXBElement<SoegRelationType> createSoegTilknyttedeEnheder(SoegRelationType value) {
        return new JAXBElement<SoegRelationType>(_SoegTilknyttedeEnheder_QNAME, SoegRelationType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     *
     */
    @XmlElementDecl(namespace = "urn:oio:sagdok:3.0.0", name = "URNIdentifikator")
    public JAXBElement<String> createURNIdentifikator(String value) {
        return new JAXBElement<String>(_URNIdentifikator_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ItSystemFlerRelationType }{@code >}}
     *
     */
    @XmlElementDecl(namespace = "urn:oio:sagdok:3.0.0", name = "TilknyttedeItSystemer")
    public JAXBElement<ItSystemFlerRelationType> createTilknyttedeItSystemer(ItSystemFlerRelationType value) {
        return new JAXBElement<ItSystemFlerRelationType>(_TilknyttedeItSystemer_QNAME, ItSystemFlerRelationType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link OrganisationEnhedFlerRelationType }{@code >}}
     *
     */
    @XmlElementDecl(namespace = "urn:oio:sagdok:3.0.0", name = "OrganisationEnhedFlerRelation")
    public JAXBElement<OrganisationEnhedFlerRelationType> createOrganisationEnhedFlerRelation(OrganisationEnhedFlerRelationType value) {
        return new JAXBElement<OrganisationEnhedFlerRelationType>(_OrganisationEnhedFlerRelation_QNAME, OrganisationEnhedFlerRelationType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link SoegRelationType }{@code >}}
     *
     */
    @XmlElementDecl(namespace = "urn:oio:sagdok:3.0.0", name = "SoegRelation")
    public JAXBElement<SoegRelationType> createSoegRelation(SoegRelationType value) {
        return new JAXBElement<SoegRelationType>(_SoegRelation_QNAME, SoegRelationType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ImportInputType }{@code >}}
     *
     */
    @XmlElementDecl(namespace = "urn:oio:sagdok:3.0.0", name = "ImportInput")
    public JAXBElement<ImportInputType> createImportInput(ImportInputType value) {
        return new JAXBElement<ImportInputType>(_ImportInput_QNAME, ImportInputType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BrugerFlerRelationType }{@code >}}
     *
     */
    @XmlElementDecl(namespace = "urn:oio:sagdok:3.0.0", name = "BrugerFlerRelation")
    public JAXBElement<BrugerFlerRelationType> createBrugerFlerRelation(BrugerFlerRelationType value) {
        return new JAXBElement<BrugerFlerRelationType>(_BrugerFlerRelation_QNAME, BrugerFlerRelationType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link OrganisationEnhedFlerRelationType }{@code >}}
     *
     */
    @XmlElementDecl(namespace = "urn:oio:sagdok:3.0.0", name = "TilknyttedeEnheder")
    public JAXBElement<OrganisationEnhedFlerRelationType> createTilknyttedeEnheder(OrganisationEnhedFlerRelationType value) {
        return new JAXBElement<OrganisationEnhedFlerRelationType>(_TilknyttedeEnheder_QNAME, OrganisationEnhedFlerRelationType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     *
     */
    @XmlElementDecl(namespace = "urn:oio:sagdok:3.0.0", name = "MaksimalAntalKvantitet")
    public JAXBElement<BigInteger> createMaksimalAntalKvantitet(BigInteger value) {
        return new JAXBElement<BigInteger>(_MaksimalAntalKvantitet_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Boolean }{@code >}}
     *
     */
    @XmlElementDecl(namespace = "urn:oio:sagdok:3.0.0", name = "GraenseIndikator")
    public JAXBElement<Boolean> createGraenseIndikator(Boolean value) {
        return new JAXBElement<Boolean>(_GraenseIndikator_QNAME, Boolean.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     *
     */
    @XmlElementDecl(namespace = "urn:oio:sagdok:3.0.0", name = "InteressefaellesskabNavn")
    public JAXBElement<String> createInteressefaellesskabNavn(String value) {
        return new JAXBElement<String>(_InteressefaellesskabNavn_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     *
     */
    @XmlElementDecl(namespace = "urn:oio:sagdok:3.0.0", name = "FoersteResultatReference")
    public JAXBElement<BigInteger> createFoersteResultatReference(BigInteger value) {
        return new JAXBElement<BigInteger>(_FoersteResultatReference_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link OrganisationFunktionFlerRelationType }{@code >}}
     *
     */
    @XmlElementDecl(namespace = "urn:oio:sagdok:3.0.0", name = "OrganisationFunktionFlerRelation")
    public JAXBElement<OrganisationFunktionFlerRelationType> createOrganisationFunktionFlerRelation(OrganisationFunktionFlerRelationType value) {
        return new JAXBElement<OrganisationFunktionFlerRelationType>(_OrganisationFunktionFlerRelation_QNAME, OrganisationFunktionFlerRelationType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BrugerFlerRelationType }{@code >}}
     *
     */
    @XmlElementDecl(namespace = "urn:oio:sagdok:3.0.0", name = "TilknyttedeBrugere")
    public JAXBElement<BrugerFlerRelationType> createTilknyttedeBrugere(BrugerFlerRelationType value) {
        return new JAXBElement<BrugerFlerRelationType>(_TilknyttedeBrugere_QNAME, BrugerFlerRelationType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link RetInputType }{@code >}}
     *
     */
    @XmlElementDecl(namespace = "urn:oio:sagdok:3.0.0", name = "RetInput")
    public JAXBElement<RetInputType> createRetInput(RetInputType value) {
        return new JAXBElement<RetInputType>(_RetInput_QNAME, RetInputType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link KlasseRelationType }{@code >}}
     *
     */
    @XmlElementDecl(namespace = "urn:oio:sagdok:3.0.0", name = "Myndighedstype")
    public JAXBElement<KlasseRelationType> createMyndighedstype(KlasseRelationType value) {
        return new JAXBElement<KlasseRelationType>(_Myndighedstype_QNAME, KlasseRelationType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link StandardReturType }{@code >}}
     *
     */
    @XmlElementDecl(namespace = "urn:oio:sagdok:3.0.0", name = "StandardRetur")
    public JAXBElement<StandardReturType> createStandardRetur(StandardReturType value) {
        return new JAXBElement<StandardReturType>(_StandardRetur_QNAME, StandardReturType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link SoegOutputType }{@code >}}
     *
     */
    @XmlElementDecl(namespace = "urn:oio:sagdok:3.0.0", name = "SoegOutput")
    public JAXBElement<SoegOutputType> createSoegOutput(SoegOutputType value) {
        return new JAXBElement<SoegOutputType>(_SoegOutput_QNAME, SoegOutputType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link IdListeType }{@code >}}
     *
     */
    @XmlElementDecl(namespace = "urn:oio:sagdok:3.0.0", name = "IdListe")
    public JAXBElement<IdListeType> createIdListe(IdListeType value) {
        return new JAXBElement<IdListeType>(_IdListe_QNAME, IdListeType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link UnikIdType }{@code >}}
     *
     */
    @XmlElementDecl(namespace = "urn:oio:sagdok:3.0.0", name = "UnikId")
    public JAXBElement<UnikIdType> createUnikId(UnikIdType value) {
        return new JAXBElement<UnikIdType>(_UnikId_QNAME, UnikIdType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link SoegRelationType }{@code >}}
     *
     */
    @XmlElementDecl(namespace = "urn:oio:sagdok:3.0.0", name = "SoegEnhedstype")
    public JAXBElement<SoegRelationType> createSoegEnhedstype(SoegRelationType value) {
        return new JAXBElement<SoegRelationType>(_SoegEnhedstype_QNAME, SoegRelationType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link AdresseFlerRelationType }{@code >}}
     *
     */
    @XmlElementDecl(namespace = "urn:oio:sagdok:3.0.0", name = "AdresseFlerRelation")
    public JAXBElement<AdresseFlerRelationType> createAdresseFlerRelation(AdresseFlerRelationType value) {
        return new JAXBElement<AdresseFlerRelationType>(_AdresseFlerRelation_QNAME, AdresseFlerRelationType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link SoegRelationType }{@code >}}
     *
     */
    @XmlElementDecl(namespace = "urn:oio:sagdok:3.0.0", name = "SoegSystemTyper")
    public JAXBElement<SoegRelationType> createSoegSystemTyper(SoegRelationType value) {
        return new JAXBElement<SoegRelationType>(_SoegSystemTyper_QNAME, SoegRelationType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link SagDokObjektType }{@code >}}
     *
     */
    @XmlElementDecl(namespace = "urn:oio:sagdok:3.0.0", name = "SagDokObjekt")
    public JAXBElement<SagDokObjektType> createSagDokObjekt(SagDokObjektType value) {
        return new JAXBElement<SagDokObjektType>(_SagDokObjekt_QNAME, SagDokObjektType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link KlasseFlerRelationType }{@code >}}
     *
     */
    @XmlElementDecl(namespace = "urn:oio:sagdok:3.0.0", name = "KlasseFlerRelation")
    public JAXBElement<KlasseFlerRelationType> createKlasseFlerRelation(KlasseFlerRelationType value) {
        return new JAXBElement<KlasseFlerRelationType>(_KlasseFlerRelation_QNAME, KlasseFlerRelationType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link OrganisationRelationType }{@code >}}
     *
     */
    @XmlElementDecl(namespace = "urn:oio:sagdok:3.0.0", name = "OrganisationRelation")
    public JAXBElement<OrganisationRelationType> createOrganisationRelation(OrganisationRelationType value) {
        return new JAXBElement<OrganisationRelationType>(_OrganisationRelation_QNAME, OrganisationRelationType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link InteressefaellesskabFlerRelationType }{@code >}}
     *
     */
    @XmlElementDecl(namespace = "urn:oio:sagdok:3.0.0", name = "TilknyttedeInteressefaellesskaber")
    public JAXBElement<InteressefaellesskabFlerRelationType> createTilknyttedeInteressefaellesskaber(InteressefaellesskabFlerRelationType value) {
        return new JAXBElement<InteressefaellesskabFlerRelationType>(_TilknyttedeInteressefaellesskaber_QNAME, InteressefaellesskabFlerRelationType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link SoegRelationType }{@code >}}
     *
     */
    @XmlElementDecl(namespace = "urn:oio:sagdok:3.0.0", name = "SoegSkatteenhed")
    public JAXBElement<SoegRelationType> createSoegSkatteenhed(SoegRelationType value) {
        return new JAXBElement<SoegRelationType>(_SoegSkatteenhed_QNAME, SoegRelationType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link OrganisationRelationType }{@code >}}
     *
     */
    @XmlElementDecl(namespace = "urn:oio:sagdok:3.0.0", name = "Tilhoerer")
    public JAXBElement<OrganisationRelationType> createTilhoerer(OrganisationRelationType value) {
        return new JAXBElement<OrganisationRelationType>(_Tilhoerer_QNAME, OrganisationRelationType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link KlasseRelationType }{@code >}}
     *
     */
    @XmlElementDecl(namespace = "urn:oio:sagdok:3.0.0", name = "Virksomhedstype")
    public JAXBElement<KlasseRelationType> createVirksomhedstype(KlasseRelationType value) {
        return new JAXBElement<KlasseRelationType>(_Virksomhedstype_QNAME, KlasseRelationType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     *
     */
    @XmlElementDecl(namespace = "urn:oio:sagdok:3.0.0", name = "InteressefaellesskabTypeTekst")
    public JAXBElement<String> createInteressefaellesskabTypeTekst(String value) {
        return new JAXBElement<String>(_InteressefaellesskabTypeTekst_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TidspunktType }{@code >}}
     *
     */
    @XmlElementDecl(namespace = "urn:oio:sagdok:3.0.0", name = "VirkningFraFilter")
    public JAXBElement<TidspunktType> createVirkningFraFilter(TidspunktType value) {
        return new JAXBElement<TidspunktType>(_VirkningFraFilter_QNAME, TidspunktType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link LivscyklusKodeType }{@code >}}
     *
     */
    @XmlElementDecl(namespace = "urn:oio:sagdok:3.0.0", name = "LivscyklusKode")
    public JAXBElement<LivscyklusKodeType> createLivscyklusKode(LivscyklusKodeType value) {
        return new JAXBElement<LivscyklusKodeType>(_LivscyklusKode_QNAME, LivscyklusKodeType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link SoegRelationType }{@code >}}
     *
     */
    @XmlElementDecl(namespace = "urn:oio:sagdok:3.0.0", name = "SoegTilknyttedeFunktioner")
    public JAXBElement<SoegRelationType> createSoegTilknyttedeFunktioner(SoegRelationType value) {
        return new JAXBElement<SoegRelationType>(_SoegTilknyttedeFunktioner_QNAME, SoegRelationType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link OrganisationFlerRelationType }{@code >}}
     *
     */
    @XmlElementDecl(namespace = "urn:oio:sagdok:3.0.0", name = "OrganisationFlerRelation")
    public JAXBElement<OrganisationFlerRelationType> createOrganisationFlerRelation(OrganisationFlerRelationType value) {
        return new JAXBElement<OrganisationFlerRelationType>(_OrganisationFlerRelation_QNAME, OrganisationFlerRelationType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ItSystemFlerRelationType }{@code >}}
     *
     */
    @XmlElementDecl(namespace = "urn:oio:sagdok:3.0.0", name = "ItSystemFlerRelation")
    public JAXBElement<ItSystemFlerRelationType> createItSystemFlerRelation(ItSystemFlerRelationType value) {
        return new JAXBElement<ItSystemFlerRelationType>(_ItSystemFlerRelation_QNAME, ItSystemFlerRelationType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link LaesInputType }{@code >}}
     *
     */
    @XmlElementDecl(namespace = "urn:oio:sagdok:3.0.0", name = "LaesInput")
    public JAXBElement<LaesInputType> createLaesInput(LaesInputType value) {
        return new JAXBElement<LaesInputType>(_LaesInput_QNAME, LaesInputType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link RelationType }{@code >}}
     *
     */
    @XmlElementDecl(namespace = "urn:oio:sagdok:3.0.0", name = "Relation")
    public JAXBElement<RelationType> createRelation(RelationType value) {
        return new JAXBElement<RelationType>(_Relation_QNAME, RelationType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link SoegRelationType }{@code >}}
     *
     */
    @XmlElementDecl(namespace = "urn:oio:sagdok:3.0.0", name = "SoegBrugerTyper")
    public JAXBElement<SoegRelationType> createSoegBrugerTyper(SoegRelationType value) {
        return new JAXBElement<SoegRelationType>(_SoegBrugerTyper_QNAME, SoegRelationType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link SoegRelationType }{@code >}}
     *
     */
    @XmlElementDecl(namespace = "urn:oio:sagdok:3.0.0", name = "SoegTilknyttedePersoner")
    public JAXBElement<SoegRelationType> createSoegTilknyttedePersoner(SoegRelationType value) {
        return new JAXBElement<SoegRelationType>(_SoegTilknyttedePersoner_QNAME, SoegRelationType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TidspunktType }{@code >}}
     *
     */
    @XmlElementDecl(namespace = "urn:oio:sagdok:3.0.0", name = "FraTidspunkt")
    public JAXBElement<TidspunktType> createFraTidspunkt(TidspunktType value) {
        return new JAXBElement<TidspunktType>(_FraTidspunkt_QNAME, TidspunktType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link KlasseRelationType }{@code >}}
     *
     */
    @XmlElementDecl(namespace = "urn:oio:sagdok:3.0.0", name = "KlasseRelation")
    public JAXBElement<KlasseRelationType> createKlasseRelation(KlasseRelationType value) {
        return new JAXBElement<KlasseRelationType>(_KlasseRelation_QNAME, KlasseRelationType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     *
     */
    @XmlElementDecl(namespace = "urn:oio:sagdok:3.0.0", name = "BrugervendtNoegleTekst")
    public JAXBElement<String> createBrugervendtNoegleTekst(String value) {
        return new JAXBElement<String>(_BrugervendtNoegleTekst_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ListInputType }{@code >}}
     *
     */
    @XmlElementDecl(namespace = "urn:oio:sagdok:3.0.0", name = "ListInput")
    public JAXBElement<ListInputType> createListInput(ListInputType value) {
        return new JAXBElement<ListInputType>(_ListInput_QNAME, ListInputType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link SoegRelationType }{@code >}}
     *
     */
    @XmlElementDecl(namespace = "urn:oio:sagdok:3.0.0", name = "SoegTilknyttedeInteressefaellesskaber")
    public JAXBElement<SoegRelationType> createSoegTilknyttedeInteressefaellesskaber(SoegRelationType value) {
        return new JAXBElement<SoegRelationType>(_SoegTilknyttedeInteressefaellesskaber_QNAME, SoegRelationType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TidspunktType }{@code >}}
     *
     */
    @XmlElementDecl(namespace = "urn:oio:sagdok:3.0.0", name = "RegistreringFraFilter")
    public JAXBElement<TidspunktType> createRegistreringFraFilter(TidspunktType value) {
        return new JAXBElement<TidspunktType>(_RegistreringFraFilter_QNAME, TidspunktType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link KlasseRelationType }{@code >}}
     *
     */
    @XmlElementDecl(namespace = "urn:oio:sagdok:3.0.0", name = "Funktionstype")
    public JAXBElement<KlasseRelationType> createFunktionstype(KlasseRelationType value) {
        return new JAXBElement<KlasseRelationType>(_Funktionstype_QNAME, KlasseRelationType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link OpretInputType }{@code >}}
     *
     */
    @XmlElementDecl(namespace = "urn:oio:sagdok:3.0.0", name = "OpretInput")
    public JAXBElement<OpretInputType> createOpretInput(OpretInputType value) {
        return new JAXBElement<OpretInputType>(_OpretInput_QNAME, OpretInputType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     *
     */
    @XmlElementDecl(namespace = "urn:oio:sagdok:3.0.0", name = "EnhedNavn")
    public JAXBElement<String> createEnhedNavn(String value) {
        return new JAXBElement<String>(_EnhedNavn_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link UnikIdType }{@code >}}
     *
     */
    @XmlElementDecl(namespace = "urn:oio:sagdok:3.0.0", name = "BrugerRef")
    public JAXBElement<UnikIdType> createBrugerRef(UnikIdType value) {
        return new JAXBElement<UnikIdType>(_BrugerRef_QNAME, UnikIdType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TidspunktType }{@code >}}
     *
     */
    @XmlElementDecl(namespace = "urn:oio:sagdok:3.0.0", name = "Tidspunkt")
    public JAXBElement<TidspunktType> createTidspunkt(TidspunktType value) {
        return new JAXBElement<TidspunktType>(_Tidspunkt_QNAME, TidspunktType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TidspunktType }{@code >}}
     *
     */
    @XmlElementDecl(namespace = "urn:oio:sagdok:3.0.0", name = "RegistreringTilFilter")
    public JAXBElement<TidspunktType> createRegistreringTilFilter(TidspunktType value) {
        return new JAXBElement<TidspunktType>(_RegistreringTilFilter_QNAME, TidspunktType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link SoegRelationType }{@code >}}
     *
     */
    @XmlElementDecl(namespace = "urn:oio:sagdok:3.0.0", name = "SoegBranche")
    public JAXBElement<SoegRelationType> createSoegBranche(SoegRelationType value) {
        return new JAXBElement<SoegRelationType>(_SoegBranche_QNAME, SoegRelationType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     *
     */
    @XmlElementDecl(namespace = "urn:oio:sagdok:3.0.0", name = "ItSystemNavn")
    public JAXBElement<String> createItSystemNavn(String value) {
        return new JAXBElement<String>(_ItSystemNavn_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BasicOutputType }{@code >}}
     *
     */
    @XmlElementDecl(namespace = "urn:oio:sagdok:3.0.0", name = "BasicOutput")
    public JAXBElement<BasicOutputType> createBasicOutput(BasicOutputType value) {
        return new JAXBElement<BasicOutputType>(_BasicOutput_QNAME, BasicOutputType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link SoegSagDokObjektType }{@code >}}
     *
     */
    @XmlElementDecl(namespace = "urn:oio:sagdok:3.0.0", name = "SoegSagDokObjekt")
    public JAXBElement<SoegSagDokObjektType> createSoegSagDokObjekt(SoegSagDokObjektType value) {
        return new JAXBElement<SoegSagDokObjektType>(_SoegSagDokObjekt_QNAME, SoegSagDokObjektType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link VirkningType }{@code >}}
     *
     */
    @XmlElementDecl(namespace = "urn:oio:sagdok:3.0.0", name = "Virkning")
    public JAXBElement<VirkningType> createVirkning(VirkningType value) {
        return new JAXBElement<VirkningType>(_Virkning_QNAME, VirkningType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link SoegRelationType }{@code >}}
     *
     */
    @XmlElementDecl(namespace = "urn:oio:sagdok:3.0.0", name = "SoegOverordnet")
    public JAXBElement<SoegRelationType> createSoegOverordnet(SoegRelationType value) {
        return new JAXBElement<SoegRelationType>(_SoegOverordnet_QNAME, SoegRelationType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     *
     */
    @XmlElementDecl(namespace = "urn:oio:sagdok:3.0.0", name = "StatusKode")
    public JAXBElement<BigInteger> createStatusKode(BigInteger value) {
        return new JAXBElement<BigInteger>(_StatusKode_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link VirksomhedRelationType }{@code >}}
     *
     */
    @XmlElementDecl(namespace = "urn:oio:sagdok:3.0.0", name = "Virksomhed")
    public JAXBElement<VirksomhedRelationType> createVirksomhed(VirksomhedRelationType value) {
        return new JAXBElement<VirksomhedRelationType>(_Virksomhed_QNAME, VirksomhedRelationType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     *
     */
    @XmlElementDecl(namespace = "urn:oio:sagdok:3.0.0", name = "UUIDIdentifikator")
    public JAXBElement<String> createUUIDIdentifikator(String value) {
        return new JAXBElement<String>(_UUIDIdentifikator_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link FlerRelationType }{@code >}}
     *
     */
    @XmlElementDecl(namespace = "urn:oio:sagdok:3.0.0", name = "FlerRelation")
    public JAXBElement<FlerRelationType> createFlerRelation(FlerRelationType value) {
        return new JAXBElement<FlerRelationType>(_FlerRelation_QNAME, FlerRelationType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     *
     */
    @XmlElementDecl(namespace = "urn:oio:sagdok:3.0.0", name = "ItSystemTypeTekst")
    public JAXBElement<String> createItSystemTypeTekst(String value) {
        return new JAXBElement<String>(_ItSystemTypeTekst_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ListOutputType }{@code >}}
     *
     */
    @XmlElementDecl(namespace = "urn:oio:sagdok:3.0.0", name = "ListOutput")
    public JAXBElement<ListOutputType> createListOutput(ListOutputType value) {
        return new JAXBElement<ListOutputType>(_ListOutput_QNAME, ListOutputType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     *
     */
    @XmlElementDecl(namespace = "urn:oio:sagdok:3.0.0", name = "FunktionNavn")
    public JAXBElement<String> createFunktionNavn(String value) {
        return new JAXBElement<String>(_FunktionNavn_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link RegistreringType }{@code >}}
     *
     */
    @XmlElementDecl(namespace = "urn:oio:sagdok:3.0.0", name = "Registrering")
    public JAXBElement<RegistreringType> createRegistrering(RegistreringType value) {
        return new JAXBElement<RegistreringType>(_Registrering_QNAME, RegistreringType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link OrganisationEnhedRelationType }{@code >}}
     *
     */
    @XmlElementDecl(namespace = "urn:oio:sagdok:3.0.0", name = "Overordnet")
    public JAXBElement<OrganisationEnhedRelationType> createOverordnet(OrganisationEnhedRelationType value) {
        return new JAXBElement<OrganisationEnhedRelationType>(_Overordnet_QNAME, OrganisationEnhedRelationType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link PersonFlerRelationType }{@code >}}
     *
     */
    @XmlElementDecl(namespace = "urn:oio:sagdok:3.0.0", name = "TilknyttedePersoner")
    public JAXBElement<PersonFlerRelationType> createTilknyttedePersoner(PersonFlerRelationType value) {
        return new JAXBElement<PersonFlerRelationType>(_TilknyttedePersoner_QNAME, PersonFlerRelationType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link SoegRelationType }{@code >}}
     *
     */
    @XmlElementDecl(namespace = "urn:oio:sagdok:3.0.0", name = "SoegTilknyttedeBrugere")
    public JAXBElement<SoegRelationType> createSoegTilknyttedeBrugere(SoegRelationType value) {
        return new JAXBElement<SoegRelationType>(_SoegTilknyttedeBrugere_QNAME, SoegRelationType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     *
     */
    @XmlElementDecl(namespace = "urn:oio:sagdok:3.0.0", name = "OrganisationNavn")
    public JAXBElement<String> createOrganisationNavn(String value) {
        return new JAXBElement<String>(_OrganisationNavn_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link UnikIdType }{@code >}}
     *
     */
    @XmlElementDecl(namespace = "urn:oio:sagdok:3.0.0", name = "AktoerRef")
    public JAXBElement<UnikIdType> createAktoerRef(UnikIdType value) {
        return new JAXBElement<UnikIdType>(_AktoerRef_QNAME, UnikIdType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     *
     */
    @XmlElementDecl(namespace = "urn:oio:sagdok:3.0.0", name = "KaldenavnTekst")
    public JAXBElement<String> createKaldenavnTekst(String value) {
        return new JAXBElement<String>(_KaldenavnTekst_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link PersonFlerRelationType }{@code >}}
     *
     */
    @XmlElementDecl(namespace = "urn:oio:sagdok:3.0.0", name = "Ansatte")
    public JAXBElement<PersonFlerRelationType> createAnsatte(PersonFlerRelationType value) {
        return new JAXBElement<PersonFlerRelationType>(_Ansatte_QNAME, PersonFlerRelationType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link SoegRelationType }{@code >}}
     *
     */
    @XmlElementDecl(namespace = "urn:oio:sagdok:3.0.0", name = "SoegVirksomhedstype")
    public JAXBElement<SoegRelationType> createSoegVirksomhedstype(SoegRelationType value) {
        return new JAXBElement<SoegRelationType>(_SoegVirksomhedstype_QNAME, SoegRelationType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link SoegRelationType }{@code >}}
     *
     */
    @XmlElementDecl(namespace = "urn:oio:sagdok:3.0.0", name = "SoegTilknyttedeOrganisationer")
    public JAXBElement<SoegRelationType> createSoegTilknyttedeOrganisationer(SoegRelationType value) {
        return new JAXBElement<SoegRelationType>(_SoegTilknyttedeOrganisationer_QNAME, SoegRelationType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link SoegRelationType }{@code >}}
     *
     */
    @XmlElementDecl(namespace = "urn:oio:sagdok:3.0.0", name = "SoegMyndighedstype")
    public JAXBElement<SoegRelationType> createSoegMyndighedstype(SoegRelationType value) {
        return new JAXBElement<SoegRelationType>(_SoegMyndighedstype_QNAME, SoegRelationType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link XMLGregorianCalendar }{@code >}}
     *
     */
    @XmlElementDecl(namespace = "urn:oio:sagdok:3.0.0", name = "TidsstempelDatoTid")
    public JAXBElement<XMLGregorianCalendar> createTidsstempelDatoTid(XMLGregorianCalendar value) {
        return new JAXBElement<XMLGregorianCalendar>(_TidsstempelDatoTid_QNAME, XMLGregorianCalendar.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link AktoerTypeKodeType }{@code >}}
     *
     */
    @XmlElementDecl(namespace = "urn:oio:sagdok:3.0.0", name = "AktoerTypeKode")
    public JAXBElement<AktoerTypeKodeType> createAktoerTypeKode(AktoerTypeKodeType value) {
        return new JAXBElement<AktoerTypeKodeType>(_AktoerTypeKode_QNAME, AktoerTypeKodeType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link SoegInputType }{@code >}}
     *
     */
    @XmlElementDecl(namespace = "urn:oio:sagdok:3.0.0", name = "SoegInput")
    public JAXBElement<SoegInputType> createSoegInput(SoegInputType value) {
        return new JAXBElement<SoegInputType>(_SoegInput_QNAME, SoegInputType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link AdresseFlerRelationType }{@code >}}
     *
     */
    @XmlElementDecl(namespace = "urn:oio:sagdok:3.0.0", name = "Adresser")
    public JAXBElement<AdresseFlerRelationType> createAdresser(AdresseFlerRelationType value) {
        return new JAXBElement<AdresseFlerRelationType>(_Adresser_QNAME, AdresseFlerRelationType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link SoegRegistreringType }{@code >}}
     *
     */
    @XmlElementDecl(namespace = "urn:oio:sagdok:3.0.0", name = "SoegRegistrering")
    public JAXBElement<SoegRegistreringType> createSoegRegistrering(SoegRegistreringType value) {
        return new JAXBElement<SoegRegistreringType>(_SoegRegistrering_QNAME, SoegRegistreringType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TidspunktType }{@code >}}
     *
     */
    @XmlElementDecl(namespace = "urn:oio:sagdok:3.0.0", name = "TilTidspunkt")
    public JAXBElement<TidspunktType> createTilTidspunkt(TidspunktType value) {
        return new JAXBElement<TidspunktType>(_TilTidspunkt_QNAME, TidspunktType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link SoegRelationType }{@code >}}
     *
     */
    @XmlElementDecl(namespace = "urn:oio:sagdok:3.0.0", name = "SoegOpgaver")
    public JAXBElement<SoegRelationType> createSoegOpgaver(SoegRelationType value) {
        return new JAXBElement<SoegRelationType>(_SoegOpgaver_QNAME, SoegRelationType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link LaesFiltreretOutputType }{@code >}}
     *
     */
    @XmlElementDecl(namespace = "urn:oio:sagdok:3.0.0", name = "LaesFiltreretOutput")
    public JAXBElement<LaesFiltreretOutputType> createLaesFiltreretOutput(LaesFiltreretOutputType value) {
        return new JAXBElement<LaesFiltreretOutputType>(_LaesFiltreretOutput_QNAME, LaesFiltreretOutputType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link SoegRelationType }{@code >}}
     *
     */
    @XmlElementDecl(namespace = "urn:oio:sagdok:3.0.0", name = "SoegAnsatte")
    public JAXBElement<SoegRelationType> createSoegAnsatte(SoegRelationType value) {
        return new JAXBElement<SoegRelationType>(_SoegAnsatte_QNAME, SoegRelationType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link OrganisationFlerRelationType }{@code >}}
     *
     */
    @XmlElementDecl(namespace = "urn:oio:sagdok:3.0.0", name = "TilknyttedeOrganisationer")
    public JAXBElement<OrganisationFlerRelationType> createTilknyttedeOrganisationer(OrganisationFlerRelationType value) {
        return new JAXBElement<OrganisationFlerRelationType>(_TilknyttedeOrganisationer_QNAME, OrganisationFlerRelationType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link OrganisationEnhedRelationType }{@code >}}
     *
     */
    @XmlElementDecl(namespace = "urn:oio:sagdok:3.0.0", name = "OrganisationEnhedRelation")
    public JAXBElement<OrganisationEnhedRelationType> createOrganisationEnhedRelation(OrganisationEnhedRelationType value) {
        return new JAXBElement<OrganisationEnhedRelationType>(_OrganisationEnhedRelation_QNAME, OrganisationEnhedRelationType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link SoegRelationType }{@code >}}
     *
     */
    @XmlElementDecl(namespace = "urn:oio:sagdok:3.0.0", name = "SoegAdresser")
    public JAXBElement<SoegRelationType> createSoegAdresser(SoegRelationType value) {
        return new JAXBElement<SoegRelationType>(_SoegAdresser_QNAME, SoegRelationType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link VirksomhedRelationType }{@code >}}
     *
     */
    @XmlElementDecl(namespace = "urn:oio:sagdok:3.0.0", name = "Skatteenhed")
    public JAXBElement<VirksomhedRelationType> createSkatteenhed(VirksomhedRelationType value) {
        return new JAXBElement<VirksomhedRelationType>(_Skatteenhed_QNAME, VirksomhedRelationType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link UuidNoteInputType }{@code >}}
     *
     */
    @XmlElementDecl(namespace = "urn:oio:sagdok:3.0.0", name = "UuidNoteInput")
    public JAXBElement<UuidNoteInputType> createUuidNoteInput(UuidNoteInputType value) {
        return new JAXBElement<UuidNoteInputType>(_UuidNoteInput_QNAME, UuidNoteInputType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     *
     */
    @XmlElementDecl(namespace = "urn:oio:sagdok:3.0.0", name = "NoteTekst")
    public JAXBElement<String> createNoteTekst(String value) {
        return new JAXBElement<String>(_NoteTekst_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link SoegRelationType }{@code >}}
     *
     */
    @XmlElementDecl(namespace = "urn:oio:sagdok:3.0.0", name = "SoegVirksomhed")
    public JAXBElement<SoegRelationType> createSoegVirksomhed(SoegRelationType value) {
        return new JAXBElement<SoegRelationType>(_SoegVirksomhed_QNAME, SoegRelationType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link SoegRelationType }{@code >}}
     *
     */
    @XmlElementDecl(namespace = "urn:oio:sagdok:3.0.0", name = "SoegProduktionsenhed")
    public JAXBElement<SoegRelationType> createSoegProduktionsenhed(SoegRelationType value) {
        return new JAXBElement<SoegRelationType>(_SoegProduktionsenhed_QNAME, SoegRelationType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     *
     */
    @XmlElementDecl(namespace = "urn:oio:sagdok:3.0.0", name = "KonfigurationReference")
    public JAXBElement<String> createKonfigurationReference(String value) {
        return new JAXBElement<String>(_KonfigurationReference_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     *
     */
    @XmlElementDecl(namespace = "urn:oio:sagdok:3.0.0", name = "FejlbeskedTekst")
    public JAXBElement<String> createFejlbeskedTekst(String value) {
        return new JAXBElement<String>(_FejlbeskedTekst_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link VirksomhedRelationType }{@code >}}
     *
     */
    @XmlElementDecl(namespace = "urn:oio:sagdok:3.0.0", name = "Produktionsenhed")
    public JAXBElement<VirksomhedRelationType> createProduktionsenhed(VirksomhedRelationType value) {
        return new JAXBElement<VirksomhedRelationType>(_Produktionsenhed_QNAME, VirksomhedRelationType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link SoegVirkningType }{@code >}}
     *
     */
    @XmlElementDecl(namespace = "urn:oio:sagdok:3.0.0", name = "SoegVirkning")
    public JAXBElement<SoegVirkningType> createSoegVirkning(SoegVirkningType value) {
        return new JAXBElement<SoegVirkningType>(_SoegVirkning_QNAME, SoegVirkningType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link OrganisationFunktionFlerRelationType }{@code >}}
     *
     */
    @XmlElementDecl(namespace = "urn:oio:sagdok:3.0.0", name = "TilknyttedeFunktioner")
    public JAXBElement<OrganisationFunktionFlerRelationType> createTilknyttedeFunktioner(OrganisationFunktionFlerRelationType value) {
        return new JAXBElement<OrganisationFunktionFlerRelationType>(_TilknyttedeFunktioner_QNAME, OrganisationFunktionFlerRelationType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link KlasseFlerRelationType }{@code >}}
     *
     */
    @XmlElementDecl(namespace = "urn:oio:sagdok:3.0.0", name = "SystemTyper")
    public JAXBElement<KlasseFlerRelationType> createSystemTyper(KlasseFlerRelationType value) {
        return new JAXBElement<KlasseFlerRelationType>(_SystemTyper_QNAME, KlasseFlerRelationType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link UnikIdType }{@code >}}
     *
     */
    @XmlElementDecl(namespace = "urn:oio:sagdok:3.0.0", name = "ReferenceID")
    public JAXBElement<UnikIdType> createReferenceID(UnikIdType value) {
        return new JAXBElement<UnikIdType>(_ReferenceID_QNAME, UnikIdType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     *
     */
    @XmlElementDecl(namespace = "urn:oio:sagdok:3.0.0", name = "BrugerNavn")
    public JAXBElement<String> createBrugerNavn(String value) {
        return new JAXBElement<String>(_BrugerNavn_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link SoegRelationType }{@code >}}
     *
     */
    @XmlElementDecl(namespace = "urn:oio:sagdok:3.0.0", name = "SoegTilhoerer")
    public JAXBElement<SoegRelationType> createSoegTilhoerer(SoegRelationType value) {
        return new JAXBElement<SoegRelationType>(_SoegTilhoerer_QNAME, SoegRelationType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link KlasseRelationType }{@code >}}
     *
     */
    @XmlElementDecl(namespace = "urn:oio:sagdok:3.0.0", name = "Enhedstype")
    public JAXBElement<KlasseRelationType> createEnhedstype(KlasseRelationType value) {
        return new JAXBElement<KlasseRelationType>(_Enhedstype_QNAME, KlasseRelationType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link VirksomhedRelationType }{@code >}}
     *
     */
    @XmlElementDecl(namespace = "urn:oio:sagdok:3.0.0", name = "VirksomhedRelation")
    public JAXBElement<VirksomhedRelationType> createVirksomhedRelation(VirksomhedRelationType value) {
        return new JAXBElement<VirksomhedRelationType>(_VirksomhedRelation_QNAME, VirksomhedRelationType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link MyndighedRelationType }{@code >}}
     *
     */
    @XmlElementDecl(namespace = "urn:oio:sagdok:3.0.0", name = "Myndighed")
    public JAXBElement<MyndighedRelationType> createMyndighed(MyndighedRelationType value) {
        return new JAXBElement<MyndighedRelationType>(_Myndighed_QNAME, MyndighedRelationType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link KlasseRelationType }{@code >}}
     *
     */
    @XmlElementDecl(namespace = "urn:oio:sagdok:3.0.0", name = "Branche")
    public JAXBElement<KlasseRelationType> createBranche(KlasseRelationType value) {
        return new JAXBElement<KlasseRelationType>(_Branche_QNAME, KlasseRelationType.class, null, value);
    }

}
