//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2011.06.14 at 09:30:07 AM CEST
//


package oio.sagdok._3_0;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;
import oio.sagdok.person._1_0.PersonRelationType;


/**
 * <p>Java class for RelationType complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="RelationType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{urn:oio:sagdok:3.0.0}Virkning"/>
 *         &lt;element ref="{urn:oio:sagdok:3.0.0}ReferenceID"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 *
 *
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "RelationType", propOrder = {
    "virkning",
    "referenceID"
})
@XmlSeeAlso({
    PersonRelationType.class,
    MyndighedRelationType.class,
    KlasseRelationType.class,
    VirksomhedRelationType.class,
    OrganisationEnhedRelationType.class,
    OrganisationRelationType.class
})
public class RelationType {

    @XmlElement(name = "Virkning", required = true)
    protected VirkningType virkning;
    @XmlElement(name = "ReferenceID", required = true)
    protected UnikIdType referenceID;

    /**
     * Gets the value of the virkning property.
     *
     * @return
     *     possible object is
     *     {@link VirkningType }
     *
     */
    public VirkningType getVirkning() {
        return virkning;
    }

    /**
     * Sets the value of the virkning property.
     *
     * @param value
     *     allowed object is
     *     {@link VirkningType }
     *
     */
    public void setVirkning(VirkningType value) {
        this.virkning = value;
    }

    /**
     * Gets the value of the referenceID property.
     *
     * @return
     *     possible object is
     *     {@link UnikIdType }
     *
     */
    public UnikIdType getReferenceID() {
        return referenceID;
    }

    /**
     * Sets the value of the referenceID property.
     *
     * @param value
     *     allowed object is
     *     {@link UnikIdType }
     *
     */
    public void setReferenceID(UnikIdType value) {
        this.referenceID = value;
    }

}
