//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2011.06.14 at 09:30:07 AM CEST
//


package oio.sagdok._3_0;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for SoegRegistreringType complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="SoegRegistreringType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{urn:oio:sagdok:3.0.0}FraTidspunkt" minOccurs="0"/>
 *         &lt;element ref="{urn:oio:sagdok:3.0.0}LivscyklusKode" minOccurs="0"/>
 *         &lt;element ref="{urn:oio:sagdok:3.0.0}BrugerRef" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 *
 *
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "SoegRegistreringType", propOrder = {
    "fraTidspunkt",
    "livscyklusKode",
    "brugerRef"
})
public class SoegRegistreringType {

    @XmlElement(name = "FraTidspunkt")
    protected TidspunktType fraTidspunkt;
    @XmlElement(name = "LivscyklusKode")
    protected LivscyklusKodeType livscyklusKode;
    @XmlElement(name = "BrugerRef")
    protected UnikIdType brugerRef;

    /**
     * Gets the value of the fraTidspunkt property.
     *
     * @return
     *     possible object is
     *     {@link TidspunktType }
     *
     */
    public TidspunktType getFraTidspunkt() {
        return fraTidspunkt;
    }

    /**
     * Sets the value of the fraTidspunkt property.
     *
     * @param value
     *     allowed object is
     *     {@link TidspunktType }
     *
     */
    public void setFraTidspunkt(TidspunktType value) {
        this.fraTidspunkt = value;
    }

    /**
     * Gets the value of the livscyklusKode property.
     *
     * @return
     *     possible object is
     *     {@link LivscyklusKodeType }
     *
     */
    public LivscyklusKodeType getLivscyklusKode() {
        return livscyklusKode;
    }

    /**
     * Sets the value of the livscyklusKode property.
     *
     * @param value
     *     allowed object is
     *     {@link LivscyklusKodeType }
     *
     */
    public void setLivscyklusKode(LivscyklusKodeType value) {
        this.livscyklusKode = value;
    }

    /**
     * Gets the value of the brugerRef property.
     *
     * @return
     *     possible object is
     *     {@link UnikIdType }
     *
     */
    public UnikIdType getBrugerRef() {
        return brugerRef;
    }

    /**
     * Sets the value of the brugerRef property.
     *
     * @param value
     *     allowed object is
     *     {@link UnikIdType }
     *
     */
    public void setBrugerRef(UnikIdType value) {
        this.brugerRef = value;
    }

}
