//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2011.06.14 at 09:30:07 AM CEST
//


package oio.sagdok._3_0;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for SoegRelationType complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="SoegRelationType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{urn:oio:sagdok:3.0.0}SoegVirkning" minOccurs="0"/>
 *         &lt;element ref="{urn:oio:sagdok:3.0.0}ReferenceID" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 *
 *
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "SoegRelationType", propOrder = {
    "soegVirkning",
    "referenceID"
})
public class SoegRelationType {

    @XmlElement(name = "SoegVirkning")
    protected SoegVirkningType soegVirkning;
    @XmlElement(name = "ReferenceID")
    protected UnikIdType referenceID;

    /**
     * Gets the value of the soegVirkning property.
     *
     * @return
     *     possible object is
     *     {@link SoegVirkningType }
     *
     */
    public SoegVirkningType getSoegVirkning() {
        return soegVirkning;
    }

    /**
     * Sets the value of the soegVirkning property.
     *
     * @param value
     *     allowed object is
     *     {@link SoegVirkningType }
     *
     */
    public void setSoegVirkning(SoegVirkningType value) {
        this.soegVirkning = value;
    }

    /**
     * Gets the value of the referenceID property.
     *
     * @return
     *     possible object is
     *     {@link UnikIdType }
     *
     */
    public UnikIdType getReferenceID() {
        return referenceID;
    }

    /**
     * Sets the value of the referenceID property.
     *
     * @param value
     *     allowed object is
     *     {@link UnikIdType }
     *
     */
    public void setReferenceID(UnikIdType value) {
        this.referenceID = value;
    }

}
