//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2011.06.14 at 09:30:07 AM CEST
//


package oio.sagdok._3_0;

import java.math.BigInteger;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for SoegInputType complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="SoegInputType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{urn:oio:sagdok:3.0.0}FoersteResultatReference" minOccurs="0"/>
 *         &lt;element ref="{urn:oio:sagdok:3.0.0}MaksimalAntalKvantitet" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 *
 *
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "SoegInputType", propOrder = {
    "foersteResultatReference",
    "maksimalAntalKvantitet"
})
public class SoegInputType {

    @XmlElement(name = "FoersteResultatReference")
    protected BigInteger foersteResultatReference;
    @XmlElement(name = "MaksimalAntalKvantitet")
    protected BigInteger maksimalAntalKvantitet;

    /**
     * Gets the value of the foersteResultatReference property.
     *
     * @return
     *     possible object is
     *     {@link BigInteger }
     *
     */
    public BigInteger getFoersteResultatReference() {
        return foersteResultatReference;
    }

    /**
     * Sets the value of the foersteResultatReference property.
     *
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *
     */
    public void setFoersteResultatReference(BigInteger value) {
        this.foersteResultatReference = value;
    }

    /**
     * Gets the value of the maksimalAntalKvantitet property.
     *
     * @return
     *     possible object is
     *     {@link BigInteger }
     *
     */
    public BigInteger getMaksimalAntalKvantitet() {
        return maksimalAntalKvantitet;
    }

    /**
     * Sets the value of the maksimalAntalKvantitet property.
     *
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *
     */
    public void setMaksimalAntalKvantitet(BigInteger value) {
        this.maksimalAntalKvantitet = value;
    }

}
