//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2011.06.14 at 09:30:07 AM CEST
//


package oio.sagdok._3_0;

import java.math.BigInteger;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for StandardReturType complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="StandardReturType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{urn:oio:sagdok:3.0.0}StatusKode"/>
 *         &lt;element ref="{urn:oio:sagdok:3.0.0}FejlbeskedTekst" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 *
 *
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "StandardReturType", propOrder = {
    "statusKode",
    "fejlbeskedTekst"
})
public class StandardReturType {

    @XmlElement(name = "StatusKode", required = true)
    protected BigInteger statusKode;
    @XmlElement(name = "FejlbeskedTekst")
    protected String fejlbeskedTekst;

    /**
     * Gets the value of the statusKode property.
     *
     * @return
     *     possible object is
     *     {@link BigInteger }
     *
     */
    public BigInteger getStatusKode() {
        return statusKode;
    }

    /**
     * Sets the value of the statusKode property.
     *
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *
     */
    public void setStatusKode(BigInteger value) {
        this.statusKode = value;
    }

    /**
     * Gets the value of the fejlbeskedTekst property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getFejlbeskedTekst() {
        return fejlbeskedTekst;
    }

    /**
     * Sets the value of the fejlbeskedTekst property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setFejlbeskedTekst(String value) {
        this.fejlbeskedTekst = value;
    }

}
