//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2011.06.14 at 09:30:07 AM CEST
//


package oio.sagdok._3_0;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for UuidNoteInputType complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="UuidNoteInputType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{urn:oio:sagdok:3.0.0}UUIDIdentifikator"/>
 *         &lt;element ref="{urn:oio:sagdok:3.0.0}NoteTekst" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 *
 *
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "UuidNoteInputType", propOrder = {
    "uuidIdentifikator",
    "noteTekst"
})
public class UuidNoteInputType {

    @XmlElement(name = "UUIDIdentifikator", required = true)
    protected String uuidIdentifikator;
    @XmlElement(name = "NoteTekst")
    protected String noteTekst;

    /**
     * Gets the value of the uuidIdentifikator property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getUUIDIdentifikator() {
        return uuidIdentifikator;
    }

    /**
     * Sets the value of the uuidIdentifikator property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setUUIDIdentifikator(String value) {
        this.uuidIdentifikator = value;
    }

    /**
     * Gets the value of the noteTekst property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getNoteTekst() {
        return noteTekst;
    }

    /**
     * Sets the value of the noteTekst property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setNoteTekst(String value) {
        this.noteTekst = value;
    }

}
