//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.3u2-hudson-jaxb-ri-2.2.3-4- 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.05.25 at 09:38:22 AM CEST 
//


package oio.sagdok._2_0;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the oio.sagdok._2_0 package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _SagDokObjekt_QNAME = new QName("urn:oio:sagdok:2.0.0", "SagDokObjekt");
    private final static QName _NoteTekst_QNAME = new QName("urn:oio:sagdok:2.0.0", "NoteTekst");
    private final static QName _UnikId_QNAME = new QName("urn:oio:sagdok:2.0.0", "UnikId");
    private final static QName _TilTidspunkt_QNAME = new QName("urn:oio:sagdok:2.0.0", "TilTidspunkt");
    private final static QName _Relation_QNAME = new QName("urn:oio:sagdok:2.0.0", "Relation");
    private final static QName _LivscyklusKode_QNAME = new QName("urn:oio:sagdok:2.0.0", "LivscyklusKode");
    private final static QName _ReferenceID_QNAME = new QName("urn:oio:sagdok:2.0.0", "ReferenceID");
    private final static QName _PersonFlerRelation_QNAME = new QName("urn:oio:sagdok:2.0.0", "PersonFlerRelation");
    private final static QName _LokalUdvidelse_QNAME = new QName("urn:oio:sagdok:2.0.0", "LokalUdvidelse");
    private final static QName _Tidspunkt_QNAME = new QName("urn:oio:sagdok:2.0.0", "Tidspunkt");
    private final static QName _URNIdentifikator_QNAME = new QName("urn:oio:sagdok:2.0.0", "URNIdentifikator");
    private final static QName _FraTidspunkt_QNAME = new QName("urn:oio:sagdok:2.0.0", "FraTidspunkt");
    private final static QName _TilstandVirkning_QNAME = new QName("urn:oio:sagdok:2.0.0", "TilstandVirkning");
    private final static QName _Registrering_QNAME = new QName("urn:oio:sagdok:2.0.0", "Registrering");
    private final static QName _KaldenavnTekst_QNAME = new QName("urn:oio:sagdok:2.0.0", "KaldenavnTekst");
    private final static QName _AktoerRef_QNAME = new QName("urn:oio:sagdok:2.0.0", "AktoerRef");
    private final static QName _Virkning_QNAME = new QName("urn:oio:sagdok:2.0.0", "Virkning");
    private final static QName _FlerRelation_QNAME = new QName("urn:oio:sagdok:2.0.0", "FlerRelation");
    private final static QName _GraenseIndikator_QNAME = new QName("urn:oio:sagdok:2.0.0", "GraenseIndikator");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: oio.sagdok._2_0
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link PersonFlerRelationType }
     * 
     */
    public PersonFlerRelationType createPersonFlerRelationType() {
        return new PersonFlerRelationType();
    }

    /**
     * Create an instance of {@link VirkningType }
     * 
     */
    public VirkningType createVirkningType() {
        return new VirkningType();
    }

    /**
     * Create an instance of {@link TidspunktType }
     * 
     */
    public TidspunktType createTidspunktType() {
        return new TidspunktType();
    }

    /**
     * Create an instance of {@link RelationType }
     * 
     */
    public RelationType createRelationType() {
        return new RelationType();
    }

    /**
     * Create an instance of {@link LokalUdvidelseType }
     * 
     */
    public LokalUdvidelseType createLokalUdvidelseType() {
        return new LokalUdvidelseType();
    }

    /**
     * Create an instance of {@link UnikIdType }
     * 
     */
    public UnikIdType createUnikIdType() {
        return new UnikIdType();
    }

    /**
     * Create an instance of {@link SagDokObjektType }
     * 
     */
    public SagDokObjektType createSagDokObjektType() {
        return new SagDokObjektType();
    }

    /**
     * Create an instance of {@link TilstandVirkningType }
     * 
     */
    public TilstandVirkningType createTilstandVirkningType() {
        return new TilstandVirkningType();
    }

    /**
     * Create an instance of {@link RegistreringType }
     * 
     */
    public RegistreringType createRegistreringType() {
        return new RegistreringType();
    }

    /**
     * Create an instance of {@link FlerRelationType }
     * 
     */
    public FlerRelationType createFlerRelationType() {
        return new FlerRelationType();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link SagDokObjektType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:oio:sagdok:2.0.0", name = "SagDokObjekt")
    public JAXBElement<SagDokObjektType> createSagDokObjekt(SagDokObjektType value) {
        return new JAXBElement<SagDokObjektType>(_SagDokObjekt_QNAME, SagDokObjektType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:oio:sagdok:2.0.0", name = "NoteTekst")
    public JAXBElement<String> createNoteTekst(String value) {
        return new JAXBElement<String>(_NoteTekst_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link UnikIdType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:oio:sagdok:2.0.0", name = "UnikId")
    public JAXBElement<UnikIdType> createUnikId(UnikIdType value) {
        return new JAXBElement<UnikIdType>(_UnikId_QNAME, UnikIdType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TidspunktType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:oio:sagdok:2.0.0", name = "TilTidspunkt")
    public JAXBElement<TidspunktType> createTilTidspunkt(TidspunktType value) {
        return new JAXBElement<TidspunktType>(_TilTidspunkt_QNAME, TidspunktType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link RelationType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:oio:sagdok:2.0.0", name = "Relation")
    public JAXBElement<RelationType> createRelation(RelationType value) {
        return new JAXBElement<RelationType>(_Relation_QNAME, RelationType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link LivscyklusKodeType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:oio:sagdok:2.0.0", name = "LivscyklusKode")
    public JAXBElement<LivscyklusKodeType> createLivscyklusKode(LivscyklusKodeType value) {
        return new JAXBElement<LivscyklusKodeType>(_LivscyklusKode_QNAME, LivscyklusKodeType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link UnikIdType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:oio:sagdok:2.0.0", name = "ReferenceID")
    public JAXBElement<UnikIdType> createReferenceID(UnikIdType value) {
        return new JAXBElement<UnikIdType>(_ReferenceID_QNAME, UnikIdType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link PersonFlerRelationType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:oio:sagdok:2.0.0", name = "PersonFlerRelation")
    public JAXBElement<PersonFlerRelationType> createPersonFlerRelation(PersonFlerRelationType value) {
        return new JAXBElement<PersonFlerRelationType>(_PersonFlerRelation_QNAME, PersonFlerRelationType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link LokalUdvidelseType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:oio:sagdok:2.0.0", name = "LokalUdvidelse")
    public JAXBElement<LokalUdvidelseType> createLokalUdvidelse(LokalUdvidelseType value) {
        return new JAXBElement<LokalUdvidelseType>(_LokalUdvidelse_QNAME, LokalUdvidelseType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TidspunktType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:oio:sagdok:2.0.0", name = "Tidspunkt")
    public JAXBElement<TidspunktType> createTidspunkt(TidspunktType value) {
        return new JAXBElement<TidspunktType>(_Tidspunkt_QNAME, TidspunktType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:oio:sagdok:2.0.0", name = "URNIdentifikator")
    public JAXBElement<String> createURNIdentifikator(String value) {
        return new JAXBElement<String>(_URNIdentifikator_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TidspunktType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:oio:sagdok:2.0.0", name = "FraTidspunkt")
    public JAXBElement<TidspunktType> createFraTidspunkt(TidspunktType value) {
        return new JAXBElement<TidspunktType>(_FraTidspunkt_QNAME, TidspunktType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TilstandVirkningType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:oio:sagdok:2.0.0", name = "TilstandVirkning")
    public JAXBElement<TilstandVirkningType> createTilstandVirkning(TilstandVirkningType value) {
        return new JAXBElement<TilstandVirkningType>(_TilstandVirkning_QNAME, TilstandVirkningType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link RegistreringType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:oio:sagdok:2.0.0", name = "Registrering")
    public JAXBElement<RegistreringType> createRegistrering(RegistreringType value) {
        return new JAXBElement<RegistreringType>(_Registrering_QNAME, RegistreringType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:oio:sagdok:2.0.0", name = "KaldenavnTekst")
    public JAXBElement<String> createKaldenavnTekst(String value) {
        return new JAXBElement<String>(_KaldenavnTekst_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link UnikIdType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:oio:sagdok:2.0.0", name = "AktoerRef")
    public JAXBElement<UnikIdType> createAktoerRef(UnikIdType value) {
        return new JAXBElement<UnikIdType>(_AktoerRef_QNAME, UnikIdType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link VirkningType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:oio:sagdok:2.0.0", name = "Virkning")
    public JAXBElement<VirkningType> createVirkning(VirkningType value) {
        return new JAXBElement<VirkningType>(_Virkning_QNAME, VirkningType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link FlerRelationType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:oio:sagdok:2.0.0", name = "FlerRelation")
    public JAXBElement<FlerRelationType> createFlerRelation(FlerRelationType value) {
        return new JAXBElement<FlerRelationType>(_FlerRelation_QNAME, FlerRelationType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Boolean }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:oio:sagdok:2.0.0", name = "GraenseIndikator")
    public JAXBElement<Boolean> createGraenseIndikator(Boolean value) {
        return new JAXBElement<Boolean>(_GraenseIndikator_QNAME, Boolean.class, null, value);
    }

}
