//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.3u2-hudson-jaxb-ri-2.2.3-4- 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.05.25 at 09:38:22 AM CEST 
//


package oio.sagdok._2_0;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for TidspunktType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="TidspunktType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;choice>
 *         &lt;element ref="{urn:oio:sagdok:1.0.0}TidsstempelDatoTid"/>
 *         &lt;element ref="{urn:oio:sagdok:2.0.0}GraenseIndikator"/>
 *       &lt;/choice>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "TidspunktType", propOrder = {
    "tidsstempelDatoTid",
    "graenseIndikator"
})
public class TidspunktType {

    @XmlElement(name = "TidsstempelDatoTid", namespace = "urn:oio:sagdok:1.0.0")
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar tidsstempelDatoTid;
    @XmlElement(name = "GraenseIndikator")
    protected Boolean graenseIndikator;

    /**
     * Gets the value of the tidsstempelDatoTid property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getTidsstempelDatoTid() {
        return tidsstempelDatoTid;
    }

    /**
     * Sets the value of the tidsstempelDatoTid property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setTidsstempelDatoTid(XMLGregorianCalendar value) {
        this.tidsstempelDatoTid = value;
    }

    /**
     * Gets the value of the graenseIndikator property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isGraenseIndikator() {
        return graenseIndikator;
    }

    /**
     * Sets the value of the graenseIndikator property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setGraenseIndikator(Boolean value) {
        this.graenseIndikator = value;
    }

}
