//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.06.14 at 09:30:07 AM CEST
//

@javax.xml.bind.annotation.XmlSchema(namespace = "urn:oio:sagdok:part:1.0.0")
package oio.sagdok.part._1_0;
